- site.yml
Add `page-component-build-list` attribute to `site.yml` as it is in `docs`.
Used in the local build to get the correct opengraph image.
Backport to 10.8 and 10.9
> Add page-component-build-list to site.yml

- modules/ROOT/partials/nav.adoc
The family ressource ID in `nav.adoc` needs to be changed from `{partialsdir}` -> `partial$`
> fix the partial family resource ID in nav.adoc

- modules/ROOT/partials/nav.adoc
> [10.9] [PR 16] fix the partial family resource ID in nav.adoc

- modules/ROOT/partials/nav.adoc
> [10.8] [PR 16] fix the partial family resource ID in nav.adoc

- modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
- modules/admin_manual/partials/installation/manual_installation/useful_tips.adoc
Moves an attribute to the correct location (from document to partial document where it gets used)
Backport to 10.9
> move attribute to correct location

- modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_18.04.adoc
- modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
- modules/admin_manual/partials/installation/manual_installation/useful_tips.adoc
References: https://github.com/owncloud/docs-server/pull/19 (move attribute to correct location)
Moves an attribute to the correct location (from document to partial document where it gets used)
This is the 10.8 part which differes a bit from master/10.9
> [10.8] [PR19] move attribute to correct location

- antora.yml
Set the version in antora.yml in single quotes, else it may get interpreted as number (Antora).
No backport, 10.8 will be an independent PR
> Fix antora.yml version 10.9 only

- antora.yml
Set the version in antora.yml in single quotes, else it may get interpreted as number (Antora).
No backport, 10.9 will be an independent PR
> Fix antora.yml version 10.8 only

- modules/admin_manual/pages/installation/manual_installation/manual_installation_apache.adoc
- modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
- modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
- site.yml
The quick install guide fails, if mpm_event is already installed.
> mpm_event conflicts with php

- modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Config-to-docs run to add the latest changes.
References:
https://github.com/owncloud/docs/issues/3502 ([OIDC] AutoProvisioning based on a Provisioning Claim)
https://github.com/owncloud/core/pull/39732 (Add wnd.listen.reconnectAfterTime config sample)
Backport to 10.9 only
> Config-to-docs Run

- modules/admin_manual/pages/installation/docker/index.adoc
This fixes the docker compose example link used by wget
Fixes: https://github.com/owncloud/docs/issues/4692 (bad URL in docker compose instructions)
> Fix docker compose example link

- modules/ROOT/pages/index.adoc
Post fix for #44
To address a page in a module you need to use following format (using version and component only if accessed from outside the repo) `xref:version@component:module:filename.adoc[]`. The family coordinate: `page$` for pages must not be used as falsly introduced by #44. While this renders correctly doing a local build, it errors for the build via docs.
Backport to 10.9 and 10.8 necessary
> Fix the resource coordinates in the introduction

- modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
- modules/admin_manual/pages/configuration/files/encryption/encryption_configuration_quick_guide.adoc
- modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
- modules/admin_manual/pages/maintenance/upgrading/package_upgrade.adoc
- modules/admin_manual/pages/maintenance/upgrading/update.adoc
- modules/admin_manual/pages/maintenance/upgrading/upgrade.adoc
- site.yml
Fixes the references to documents in docs, eg release notes.
> Fix broken antora component links to docs

- modules/admin_manual/examples/installation/manual_installation/owncloud_prep.sh
- modules/admin_manual/pages/installation/manual_installation/manual_installation.adoc
- modules/admin_manual/pages/installation/manual_installation/script_guided_install.adoc
- modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
- site.yml
Fixes: https://github.com/owncloud/enterprise/issues/5019 ([Documentation from Manual Upgrade generates problems by the Customers](https://github.com/owncloud/enterprise/issues/5019#))
Improves the manual upgrade documentation.
@cdamken fyi
> Update manual upgrade documentation

- modules/developer_manual/pages/app/advanced/extstorage.adoc
- modules/developer_manual/pages/app/advanced/notifications.adoc
- modules/developer_manual/pages/app/fundamentals/backgroundjobs.adoc
- modules/developer_manual/pages/app/fundamentals/database.adoc
- modules/developer_manual/pages/app/fundamentals/filesystem.adoc
- modules/developer_manual/pages/core/apis/ocs-capabilities.adoc
- modules/developer_manual/pages/core/apis/ocs-notification-endpoint-v1.adoc
- modules/developer_manual/pages/core/apis/ocs-notify-public-link-by-email.adoc
- modules/developer_manual/pages/core/apis/ocs-recipient-api.adoc
- modules/developer_manual/pages/core/apis/ocs-share-api.adoc
- modules/developer_manual/pages/core/apis/ocs-totp-validation-api.adoc
- modules/developer_manual/pages/core/apis/ocs-user-sync-api.adoc
- modules/developer_manual/pages/core/apis/roles-api.adoc
- modules/developer_manual/pages/core/theming.adoc
- modules/developer_manual/pages/general/backporting.adoc
- modules/developer_manual/pages/testing/acceptance-tests.adoc
- modules/developer_manual/pages/testing/unit-testing.adoc
- modules/developer_manual/pages/webdav_api/groups/custom_groups_endpoints.adoc
- modules/developer_manual/pages/webdav_api/groups/group_membership_endpoints.adoc
- modules/developer_manual/pages/webdav_api/meta.adoc
- modules/developer_manual/pages/webdav_api/public_files.adoc
- modules/developer_manual/pages/webdav_api/search/_filter_files.adoc
- modules/developer_manual/pages/webdav_api/search/_search_files.adoc
- modules/developer_manual/pages/webdav_api/trashbin.adoc
- modules/developer_manual/partials/webdav_api/files_versions/list_files_versions.adoc
- modules/developer_manual/partials/webdav_api/search/common_error_responses.adoc
Renames the family coordinate from {examplesdir} to example$ to be prepared for Antora 3
This is for the dev manual only as all branches have only a view differences. The admin manual will get its own PR.
Backport to10.9 and 10.8
> Dev: rename {examplesdir} with example$

- modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
- modules/admin_manual/pages/enterprise/user_management/user_auth_shibboleth.adoc
- modules/admin_manual/pages/installation/apps_management_installation.adoc
- modules/admin_manual/pages/installation/deployment_recommendations.adoc
- modules/admin_manual/pages/installation/docker/index.adoc
- modules/admin_manual/pages/installation/letsencrypt/using_letsencrypt.adoc
- modules/admin_manual/pages/installation/manual_installation/manual_installation_apache.adoc
- modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Renames the family coordinate from {examplesdir} to example$ to be prepared for Antora 3
This is for the admin manual only because branches may have some differences. The dev manual will get its own PR.
Backport to10.9 and 10.8
> Admin: rename {examplesdir} with example$

- modules/developer_manual/pages/app/fundamentals/info.adoc
- modules/developer_manual/pages/core/apis/index.adoc
- modules/developer_manual/pages/testing/index.adoc
- modules/developer_manual/pages/webdav_api/files_versions.adoc
- modules/developer_manual/pages/webdav_api/groups/custom_groups_endpoints.adoc
- modules/developer_manual/pages/webdav_api/groups/group_membership_endpoints.adoc
- modules/developer_manual/pages/webdav_api/index.adoc
- modules/developer_manual/pages/webdav_api/meta.adoc
- modules/developer_manual/pages/webdav_api/search/_filter_files.adoc
- modules/developer_manual/pages/webdav_api/search/_search_files.adoc
Renames the family coordinate from {partialsdir} to partial$ to be prepared for Antora 3
This is for the dev manual only as all branches have only a view differences. The admin manual will get its own PR.
Backport to10.9 and 10.8
> Dev: rename {partialsdir} with partial$

- modules/admin_manual/partials/nav.adoc
The Installation Wizard had the wrong position. Its intent was under manual installation and not that same level.
> Shift the wizard location by one to the left

- modules/admin_manual/partials/maintenance/major_release_note.adoc
> [10.8] [PR 95] Include the PHP version in the Requirements cell referenced in upgrade.adoc

- modules/admin_manual/partials/maintenance/major_release_note.adoc
> [10.9] [PR 95] Include the PHP version in the Requirements cell referenced in upgrade.adoc

- modules/developer_manual/examples/core/apis/ocs-capabilities/list-capabilities-response.json
- modules/developer_manual/pages/core/apis/ocs-capabilities.adoc
Part of issue #109 
Note: after core PR https://github.com/owncloud/core/pull/39143 is merged, a config-to-docs run is needed. `pollinterval` was not previously mentioned in config.sample.php and is added in that PR.
No backport needed - this will be in the next oC10 release (might be numbered 10.10.0)
> Adjust pollinterval in docs

- modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
- Additional module php-opcache explicitly installed as required for supported setup
- Removed unnecessary packages
- Split out apt installation and pecl installation into 2 code boxes, as copy paste doesn't work otherwise
- Added additonal packages ldap-utils and smbclient for troubleshooting
- Cleaned up Apache configuration
> Ubuntu 20.04 Quick Guide improvements

- modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
One step is mentioned, but it takes actually 3 steps.
Without the third one, we run into https://github.com/owncloud/encryption/issues/327#issuecomment-1049845296
> Enable encryption via occ is incomplete and leads to deprecated user-key mode

- modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
> [10.8] [PR 117] Enable encryption via occ is incomplete and leads to deprecated user-key mode

- modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
> [10.9] [PR 117] Enable encryption via occ is incomplete and leads to deprecated user-key mode

- modules/admin_manual/pages/configuration/server/harden_server.adoc
- modules/admin_manual/pages/qnap/index.adoc
Missed fixes for the harden server document
Note related, but added a qnap text fix as it needs the same backporting
> Source language fix for harden server

- modules/admin_manual/pages/configuration/database/db_conversion.adoc
innodb_read_io_threads and innodb_write_io_thread defaults to 4, no need to change the defaulr
innodb_flush_log_at_trx_commit=1 is the default as well
innodb_thread_concurrency does nothing since  mariadb 10.5.5
innodb_file_per_table=ON same
innodb_large_prefix = 1 is a no-op, has not done anything since maria db 10.3
> Updates to innodb tunning instructions,

- modules/ROOT/partials/nav.adoc
- site.yml
This PR **inactivates** the user guide.
We do the transition of the user guide from this repo to docs-webui in three steps:
1. Add the `docs-webui` repo which contains the user guide from server in `docs`
2. Comment out the user guide entry in the navigation
3. Remove the user guide from this repo including all necessary link fixes
Merge only when https://github.com/owncloud/docs/pull/4711 (Add user guides) has been merged.
> Inactivate the user guide

- modules/admin_manual/pages/configuration/files/external_storage/smb.adoc
- modules/admin_manual/pages/configuration/server/index_php_less_urls.adoc
- modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_ransomware_protection_commands.adoc
- modules/admin_manual/pages/configuration/server/security/oauth2.adoc
- modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
- modules/admin_manual/pages/installation/deployment_recommendations.adoc
- modules/admin_manual/pages/installation/linux_packetmanager_install.adoc
- modules/admin_manual/partials/maintenance/major_release_note.adoc
- modules/developer_manual/pages/testing/test-pilots.adoc
- modules/developer_manual/pages/webdav_api/files_versions.adoc
This PR fixes some broken internal links which were found after a full build post the user manual move with `htmltest`. Note that this are not broken links because of the migration.
(Note that we have to check the 10.8 backport for stuff not belonging to there...)
> Fix some broken links found after migrating the user manual

- modules/admin_manual/pages/installation/system_requirements.adoc
Small fix to correct a link (reference is not present) + text that is not intended to be in 10.8
No backport, 10.8 only
> Correct system requirement text for 10.8 only

- modules/admin_manual/pages/configuration/search/index.adoc
- modules/admin_manual/pages/configuration/server/security/oauth2.adoc
Fixing a broken link to an occ command in `configuration/server/security/oauth2.adoc`
Small text fix included
> Broken internal link fix

- modules/admin_manual/pages/configuration/database/linux_database_configuration.adoc
Improving readbility of the Linux database configuration with respect to 4-byte Unicode support.
Note that the content stays the same, but rendering has improved to ease readability.
> Small text improvement for the linux database configuration document

- modules/admin_manual/pages/configuration/database/linux_database_configuration.adoc
A blank (white space) sneaked accidentially...
No backport needed, already corrected in the other branches.
> Remove blank

- modules/admin_manual/pages/installation/manual_installation/manual_installation_db.adoc
postgresql install instructions facelift.
- add missing dependency package (for ubuntu)
- do not mess with postgres user - (that is a super administrator with all permissions.)
- instead add an owncloud user who only has control over the owncloud database.
(With `occ maintenance:install` the `--database pgsql` parameter choses postgresql  -- not sure, where this information would fit...)
I assume, postgresql 12 and 13, 14 work just fine with owncloud.
An official statement about supported versions should come from the nepal QA team, they start testing now.
> expand install hints for postgresql (a bit)

- modules/admin_manual/pages/enterprise/installation/oracle_db_configuration.adoc
The description to install `oci8` needs a correct version for pecl because there are different oci8 versions available for different php versions.
@jnweiger fyi
> Define the correct oci8 release for pecl because of PHP7.x

- modules/admin_manual/pages/enterprise/installation/oracle_db_configuration.adoc
> [10.9] [PR 190] Define the correct oci8 release for pecl because of PHP7.x

- modules/admin_manual/pages/enterprise/installation/oracle_db_configuration.adoc
> [10.8] [PR 190] Define the correct oci8 release for pecl because of PHP7.x

- modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_maintenance_commands.adoc
References: https://github.com/owncloud/docs-server/pull/185 (expand install hints for postgresql (a bit))
The maintenance command description was messed up including that `install` was not described.
* Adding missing commands and options
Note that the db-type `oci` (Oracle) was missing completely, see [available db types in core](https://github.com/owncloud/core/blob/817f54f53d64249166feaa0eb9231c50ca1ed7e0/lib/private/Setup.php#L127)
* Removing common options that are described on top of the occ command set
* Reordering content the way as the list (alphabetical) is set up
@jnweiger FYI
> Revision of the occ maintenance command description

- modules/admin_manual/pages/enterprise/clients/creating_branded_apps.adoc
`https://doc.owncloud.com/branded_clients/` --> `https://doc.owncloud.com/branded_clients/next/`
> Fix links to branded clients URL

- modules/admin_manual/pages/appliance/configuration/clamav.adoc
- modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
- modules/admin_manual/pages/installation/deployment_recommendations.adoc
- modules/admin_manual/pages/installation/letsencrypt/using_letsencrypt.adoc
While working on oCIS, I identified that quoted text need to be defined slightly different. This PR fixes this issue and uses the appropriate definition where neccesary. Not all texts remain quoted but defined as it should be. Note that quoted text in antora 2.3 can be encapsuled with `""` OR `____` (4x underline) while it is `____` (4x underline) with antora 3 only.
> Prepare quoted text to be Antora 3 compliant

- modules/admin_manual/pages/installation/system_requirements.adoc
We have run the automated CI using pgsql 11, 12, 13 and 14 and no problems have been found.
See https://github.com/owncloud/enterprise/issues/5064 for the discussion and links to test PRs.
All these pgsql releases are working with both ownCloud server 10.9.1 and the current server core master.
We didn't test with ownCloud server 10.8 - so I suggest that we do not backport the support doc change to 10.8.
We can advertise support for these pgsql versions. Backport to 10.9 branch.
> Add support for pgsql 11 12 13 14

- modules/admin_manual/pages/enterprise/external_storage/onedrive.adoc
The files_onedrive repository is private, this usually indicates that the app is a so called "consulting app" and only provided through (pre-)sales.
Perhaps @CaptionF @ChrisEdS you could confirm the actual process for access to this app?
> onedrive app is not a standard enterprise app

- modules/admin_manual/pages/configuration/server/harden_server.adoc
-  brcrypt does not limit the password to 72 chars due to the reasons stated, but due to the limits of the underlying cipher it uses (blowfish) which only fully mixes up to 448 bits (56 chars) of the key.. but most implementations place an absolute limit of 576 bit  (72 chars) 
- Remove the section about /dev/urandom, it is clumsily worded and outdated, PHP now only uises /dev/urandom as a fallback and raises errors or exceptions if it cannot be opened. rfc4086 is not relevant to owncloud, meither to PHP which just consumes the OS entropy sources.
> Updates to hardening guide

- modules/admin_manual/pages/installation/docker/index.adoc
- modules/admin_manual/pages/maintenance/backup_and_restore/backup.adoc
Fixes: https://github.com/owncloud/docs-server/issues/256 (Database backup command misses transaction parameter)
Also checked the standard backup page.
> MySQL Backup Use Single Transaction

- modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Referencing: https://github.com/owncloud/wopi/issues/195 (Docu needed: Wopi 1.6.0 will support a new business user feature)
The key `wopi.business-flow.enabled` is now added to the config key list
> Add WOPI Business Key

- modules/admin_manual/pages/enterprise/document_classification/classification_and_policy_enforcement.adoc
- modules/admin_manual/pages/enterprise/document_classification/index.adoc
- modules/admin_manual/partials/nav.adoc
The `files_classifier` app available on marketplace https://marketplace.owncloud.com/apps/files_classifier points to https://doc.owncloud.com/server/latest/admin_manual/enterprise/classification_and_policy_enforcement.html
which does not existent atm.
The document needed is:
* at the wrong location
* does not have the name needed
To be inline with the enterprise document scheme, the document has been moved, renamed and aliased properly.
@ChrisEdS @xoxys FYI
> Relocate files_classifier document

- modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Config To Docs run based on recent changes in core.
Backport to 10.9 and 10.8 **BUT** with special care as not all changes belong to those branches...
Needs manual intervention when backporting
**No  backport at all:**
`=== Enable to force user logout`
`=== Define the suggested poll interval for clients`
**No backport to 10.8:**
`=== Enable propfind depth infinity requests`
> Config To Docs run

- modules/admin_manual/pages/configuration/files/manual_file_locking.adoc
for 10.9 onwards, the section for manual file locking has been changed from `Additional` to `General`
ref https://doc.owncloud.com/docs/next/server_release_notes.html#manual-file-locking-ability-to-define-user-groups-that-can-unlock-files
> Update the section for manual file locking in admin settings

- site.yml
Adding global attribute for ocis.
Referencing: https://github.com/owncloud/docs/pull/4738
> Adding global attribute for ocis

- modules/admin_manual/pages/enterprise/external_storage/enterprise_only_auth.adoc
The feature is strange and largely unknown, and the syntax is likely to be changed again in future.
Closes: #311 
Backports to 10.10, 10.9
(no idea, if 10.8 is also affected...)
> New syntax for config stored passwords

- modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
Wrong ticks were used in one config parameter..
> Fixing ticks in msoffice-wopi

- modules/developer_manual/pages/core/apis/ocs-share-api.adoc
> [10.10] [PR 357] shareType can't be optional if shareType is 1 or 0

- modules/developer_manual/pages/core/apis/ocs-share-api.adoc
> [10.8] [PR 357] shareType can't be optional if shareType is 1 or 0

- modules/developer_manual/pages/core/apis/ocs-share-api.adoc
> [10.9] [PR 357] shareType can't be optional if shareType is 1 or 0

- modules/admin_manual/pages/installation/manual_installation/manual_installation_prerequisites.adoc
- modules/admin_manual/pages/installation/system_requirements.adoc
This is a warning and description for a temporary fix for openSSL v3.
References:
https://github.com/owncloud/core/issues/40071 ([QA] Encryption cannot be enabled on Ubuntu 22.04)
Language review welcomed.
Note this PR complements, but is **not** dependent on the Pull Request U22.04 / PHP7.4  https://github.com/owncloud/docs-server/pull/369 (Server Preparation for Ubuntu 22.04) 
@pako81 @jnweiger @IljaN fyi
> Temporary fix for the openSSL v3 incompatibility

- modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
- modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_22.04.adoc
- modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
- modules/admin_manual/pages/installation/quick_guides/ubuntu_22_04.adoc
- modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
Make the openSSL prerequisite more prominent.
> Make the openSSL prerequisite more prominent

- modules/admin_manual/pages/configuration/server/occ_command.adoc
- modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_custom_groups.adoc
- modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_config_commands.adoc
- modules/admin_manual/pages/configuration/user/user_management.adoc
This PR adds the missing occ commands for custom groups + some text addons/fixes to teh user management related to custom groups.
Language review welcomed
Backport to 10.10,10.9 and 10.8
I need to adapt https://github.com/owncloud/docs-webui/pull/41 (the driver for this PR) to link to the user_management part to refere administration.
> occ custom groups

- site.yml
Just a minor change to remove an ocis attribute no longer used and updating another attribute value (no render impact).
> Remove an ocis attribute no longer used

- site.yml
> [10.9] [PR 431] Remove an ocis attribute no longer used

- site.yml
> [10.8] [PR 431] Remove an ocis attribute no longer used

- modules/developer_manual/pages/testing/unit-testing.adoc
phpunit needs a fixed release number in the url, "latest" results in a 404
> fix phpunit url to prevent a 404

- modules/admin_manual/pages/enterprise/document_classification/classification_and_policy_enforcement.adoc
Finding broken links is a painful manual process to identify real broken links from false positives. Therefore you have to turn some rounds to get things done... This time one more catched in the admin manual.
> fix vda url

- modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
Fixes: https://github.com/owncloud/docs-server/issues/449 (Transferring Files to Another User //Specification)
Updates the files sharing configuration page:
* fixing #449 
* additional text fixes, remove not necessary linebreakes etc
* update tables
Language review welcomed.
@dpapac fyi
> Update files sharing configuration

- modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
Prefixing the occ command with php is not required nowadays as the occ command contains a shebang.
> Removed all occurrences of php prefixing

- modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Referencing: https://github.com/owncloud/core/pull/40148 (Add configuration option to bypass proxy settings for some domains)
NO backports, master only!
> Config-to-docs run to include new config elements coming from core

- modules/admin_manual/pages/configuration/server/occ_command.adoc
- modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
* The manual upgrade missed that we need to set occ to executeable.
* Speeded up the commands by using xargs
* Added *config.php and *.json to be copied to the new config directory
References: https://github.com/owncloud/docs-server/pull/472#commitcomment-76974777
@d7oc fyi
> Fixing that occ needs to be set to executable if not already done.

- modules/admin_manual/pages/installation/letsencrypt/apache.adoc
I don't know whether the Apache configuration is case-insensitive or not, but the correct parameter name is `VirtualHost` not `virtualHost` -> https://httpd.apache.org/docs/2.4/mod/core.html#virtualhost
> Corrected upper and lower case

- modules/admin_manual/pages/configuration/server/security/jquery_warnings.adoc
Update of the jQuery warning page, references: https://github.com/owncloud/core/issues/37463 (JQuery 1.2 < 3.5.0 XSS) 
> Update jQuery warnings page

- modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
`config-to-docs` run based on recent changes in core,
see https://github.com/owncloud/core/pull/40182 (Enhanced clustered-instance mode documentation)
@d7oc fyi
> Config-to-docs run based on recent changes from core

- modules/admin_manual/pages/configuration/server/caching_configuration.adoc
In order for owncloud to read the redis socket, it only needs to be added to the redis group. The redis user shouldn't be modified to make www-data its primary group.
> Make www-data a user in the redis group

- modules/admin_manual/pages/configuration/files/big_file_upload_configuration.adoc
Improved sentence about PHP output buffering as this is already the default in our tarball's `.htaccess`.
> Improved sentence about PHP output buffering

- modules/admin_manual/pages/installation/system_requirements.adoc
- modules/admin_manual/partials/installation/manual_installation/mariadb.adoc
See core PRs https://github.com/owncloud/core/pull/40206 and https://github.com/owncloud/core/pull/40207 for a demonstration that Mariadb 10.7 and 10.8 work fine with ownCloud core. That should be true from ownCloud 10.9, when support for Mariadb 10.6 was explicitly added. There are no ownCloud core code changes needed for Mariadb 10.7 or 10.8.
IMO, we can mention that ownCloud core 10.9 and upwards supports using Mariadb all the way up to 10.8.
> Document that ownCloud 10.9 and above also works with Mariadb 10.7 and 10.8

- modules/admin_manual/examples/installation/docker/docker-compose.yml
Increase the mariadb version to 10.6 in the dockerfile + comment that it needs oC 10.9
> Increased mariadb version in docker compose file

- modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
- modules/admin_manual/pages/troubleshooting/general_troubleshooting.adoc
ownCloud's `.htaccess` file will be overwritten on update. So readers should be aware of this when changing something in there.
> Added note about overwritten .htaccess file

- modules/admin_manual/pages/installation/docker/index.adoc
Having followed the instructions and using the provided `docker-compose.yml` file, the generated volume name is different from what is mentioned in the docs.
[modules/admin_manual/examples/installation/docker/docker-compose.yml](https://github.com/owncloud/docs-server/blob/master/modules/admin_manual/examples/installation/docker/docker-compose.yml)
My docker version is "Docker version 20.10.12, build 20.10.12-0ubuntu4" if that matters.
```bash
$ docker volume ls
DRIVER    VOLUME NAME
local     owncloud-setup_files
local     owncloud-setup_mysql
local     owncloud-setup_redis
```
> Update generated volume name in index.adoc

- modules/developer_manual/examples/core/scripts/curl/create-share.sh
- modules/developer_manual/pages/core/apis/ocs-share-api.adoc
Fixes #572 
Note: the ownCloud core behavior when creating public link shares is that if I ask for permissions 3 (read and update) on a public link share API share creation request, then I actually get just permission 1 (read). That has been that way for "a long time" (tm), and maybe there are existing clients that "accidentally" send permissions 3 when actually they only expect to get a public link share with read permission. (Probably requests asking for permission 3 on a public link should have returned some 4xxx code to indicate that the request is not valid, but it's too late for that now)
So that behavior needs to be preserved.
To create a public link share of a single file, the client has to request permissions 15 (read, update, create, delete) to actually get permissions 3 (read, …
> Public link share of a single file can now have edit access

- modules/admin_manual/pages/configuration/server/logging/logging_configuration.adoc
- modules/admin_manual/pages/troubleshooting/providing_logs_and_config_files.adoc
- modules/admin_manual/partials/nav.adoc
- site.yml
Fixes: [configreport application unknown to marketplace -> misleading](https://github.com/owncloud/docs-server/issues/579#top)
* fixes configreport - marketplace
* fixes logging navigation (note no link changes)
* text fixes
* repo only - fixes occ command attribute - an own PR in docs will be made to publish it 
Note that there are only a few text changes made but due to removing linebreakes, it offers to have a text review too - language review welcomed
> Fix configreport and logging

- modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Config to docs run from latest core changes
Replaces: #586 (Update config_sample_php_parameters.adoc)
> Config-to-docs run from latest core changes

- modules/admin_manual/pages/configuration/server/activity_configuration.adoc
Fixes: #592 ([QA] describe expectatins about expiry notifications)
Add some info about the time base when it comes to email notifications for expired shares and default expiration dates.
There will be an additional PR in webui to tell the same from the user pov.
Note that the activity app is part of the shipment but also can be downloaded from marketplace. Backport is needed therefore.
> Update activity app

- modules/admin_manual/pages/configuration/general_topics/impersonate_users.adoc
Fixes: [Shibboleth users cannot impersonate](https://github.com/owncloud/docs-server/issues/111#top)
Beside that, removing not necessary line breakes and image fixes.
> Fix Impersonate not working with Shibboleth

- .drone.star
- site.yml
These are the changes necessary to finalize the creation of the 10.11 branch.
The 10.11 branch is already pushed and prepared and is included in the branch protection rules.
When 10.11 (core) is finally out, the 10.9 branch can be archived,
see step 3 in  https://github.com/owncloud/docs/blob/master/docs/new-version-branch.md
Note, that the 10.11 branch in this repo is already created, but the `latest` pointer on the web
will be set to it automatically when the tag in core is set. This means, that in the docs homepage,
`latest` will point to 10.9 until the tag in core is set accordingly. When merging this PR,
10.9 will be dropped from the web but is available via pdf as usual.
Note, this PR must be merged before the 10.11 tag in core is set to avoid a 404 for `latest`.
Before merging this …
> Changes necessary for 10.11

- modules/admin_manual/pages/configuration/server/occ_command.adoc
- modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_managing_background_jobs.adoc
- modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_previews_commands.adoc
Fixes: #498 (Command to delete orphaned previews/thumbnails)
Adding a new occ command to cleanup previews
Backport to 10.11 only 
Technically ready, but draft atm because a QA clarification is necessary
@jnweiger
> occ previews:cleanup

- modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_previews_commands.adoc
References: #617 (occ previews:cleanup)
Added a missing dash in the option, fixed already in the backport of #617
No backport
> Fix occ preview command

- modules/admin_manual/pages/configuration/server/occ_command.adoc
A source block in the main occ page needed a fix.
Backport to 10.11, 10.10 and 10.9
> Fix occ source block

- modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
- modules/admin_manual/pages/configuration/server/occ_command.adoc
- modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_sharing_commands.adoc
- modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_system_command.adoc
Fixes: https://github.com/owncloud/docs-server/issues/273 (background_jobs_configuration.adoc correction)
Two fixes:
* Correct the location of the occ system commands page
This was falsly located in partials as part of the sharing page. No page additionally references this partial - moving
* Correcting the command in the bg jobs config page
Backport to 10.11, 10.10 and 10.9
> Move occ system commands to the correct location

- modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
References: https://github.com/owncloud/core/pull/40374 ([docs-only] Revert "config.apps.sample changes")
Config-to-docs Update because of a regression that needed a revert.
Backport to 10.11 only
@DeepDiver1975 fyi
> Config-to-docs Update

- modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_previews_commands.adoc
Update of the `occ previews:cleanup` command. Some important info is added.
Backport to 10.11
> Preview cleanup update

- modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
Adding some comments in `s3_compatible_object_storage_as_primary.adoc`
> doc update for owncloud/core#40389

- modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
Related to: https://central.owncloud.org/t/server-failed-but-still-have-old-s3-data/39464/4
> add hint for db backups while using s3

- modules/admin_manual/pages/configuration/integration/ms-teams.adoc
While using the [Apache Header](https://httpd.apache.org/docs/current/mod/mod_headers.html) `merge` directive an existing header it is separated from the existing header with a comma. This is invalid for CSP and result in a broken syntax. To work around this issue, an `edit*` directive can be used for a search and replace.
> fix apache header merge command

- modules/admin_manual/pages/configuration/user/user_management.adoc
This updates the user management documentation.
* added a xref pointing  to occ
* added some text at the login name
* removed not necessary linebreakes
* small text fixes
> Update the user management documentation

- modules/admin_manual/pages/configuration/user/user_management.adoc
The existing explanation was not correct. Files in a file share always count against the quota of the user who is the "owner" of the share.
I edited and added words - please review.
And I suspect that we address this quota stuff elsewhere in the docs? Can someone have a look, because if we already explain it somewhere else, then we can just link to that.
> Fixup quota explanation

- modules/admin_manual/examples/installation/docker/docker-compose.yml
- modules/admin_manual/pages/installation/docker/index.adoc
Fixes: https://github.com/owncloud/docs-server/issues/692
Related to: https://github.com/owncloud-docker/base/pull/238
> add documentation for trusted domain container env

- modules/developer_manual/pages/testing/acceptance-tests.adoc
Adds documentation about the feature file organization in the ownCloud test bases.
Fixes: https://github.com/owncloud/docs-server/issues/696
---
Signed-off-by: Kiran Parajuli <kiranparajuli589@gmail.com>
> Add feature file organization documentation

- modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
Fixes: #675 ([QA] new config.php setting with files_primary_s3)
Adding two new config parameters for S3 Primary (Allow configurable concurrent uploads)
@jnweiger FYI
> Update S3 Primary documentation

- modules/admin_manual/pages/configuration/user/user_auth_twofactor.adoc
We get questions around this a lot, and I usually link to the blog post:
https://owncloud.com/de/news/how-to-use-two-factor-authentication-with-the-owncloud-desktop-client-or-mobile-apps/
But this information should also be available in the docs.
@mmattel @EParzefall please polish
> Clarify 2FA usage with desktop and mobile apps

- modules/admin_manual/pages/installation/letsencrypt/apache.adoc
Fixes: #720 (Let's Encrypt with Apache2 currently has a slight error)
The VirtualHost definition contained an error: `VirtualHost *.80` --> `VirtualHost *:80`
> Fix VirtualHost parameter

- modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Fixes: #665 ([QA] openid-connect.basic_auth_guest_only)
**ONLY MERGE** when https://github.com/owncloud/core/pull/40481 (Config Sample update for openidconnect) has been merged.
> Config-to-docs run for openidconnect

- modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_file_commands.adoc
Fixes: #742 (occ files:scan doesn't work on S3)
Add a note to the occ files:scan command not to be used with S3.
> Update files:scan not to be used with S3

- modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
Line 22 says:
```
When downloading, the files are scanned again to prevent infections to spread, which were not known by the scanner at the time of the upload and therefore missed.
```
But line 207 said:
```
Files are checked when they are uploaded or updated but _not_ when they are downloaded.
```
Those are contradictory. I have adjusted line 207 (assuming that line 22 is correct these days)
> Files are also scanned on download

- antora.yml
References: https://github.com/owncloud/docs/pull/4792 (Rename Classic Server (no reference changes))
Renaming the headlines `Classic Server` to `ownCloud Server` on request of @dragotin.
Note no changes to references are made, optical change only.
Only merge when the referenced PR has been merged.
> Rename Classic Server (no reference changes)

- antora.yml
Reverts the version changed in #754 ([10.10] [PR 752] Rename Classic Server (no reference changes))
> Fix antora.yml (the backport overwrote accidentially the version)

- modules/admin_manual/pages/configuration/files/external_storage/configuration.adoc
- modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_file_commands.adoc
Fixes: #761 (Please clarify if file:scan works for external storages)
* Make the topic more visible by changing from NOTE to IMPORTANT
* Add info about also in external storage configuration
* Make the entries in ext stor conf itemized for better visibility
> Improve visibility that files:scan is not possible for S3

- modules/admin_manual/pages/configuration/files/external_storage/configuration.adoc
- modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_file_commands.adoc
> [10.11] [PR 762] Improve visibility that files:scan is not possible for S3

- modules/ROOT/pages/index.adoc
Missed: `ownCloud Classic Server`--> `ownCloud Server`
> Fix a remnant of the term classic

- modules/admin_manual/pages/configuration/user/guests_app.adoc
Fixes: #771 ([QA] guests app blocklist description missing)
Adding proper descriptions when using blocklists
> Update of the guest app description

- modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
Fixes: #778 (Permissions setting command fails due to incorrect sudo usage)
The piped part of the command needs sudo too.
> Add sudo on piped commands

- modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
Often mod_rewrite is auto-enabled in stock apache installations, so this ommission is quite harmless.
As the text mentions .htaccess as a possible file for the RewriteRule, the syntax should be without leading /. With a / it will never match from within the .htaccess file.
The syntax for a separate /etc/apache2/conf-available/oidc.conf file is very different:
```
<Location /.well-known/openid-configuration >
RewriteEngine on
RewriteRule .* /index.php/apps/openidconnect/config [P]
</Location>
SSLProxyEngine On     #This can be omitted if no SSL is used
```
> Apache rewriteRule requires mod_rewrite and no leading / in .htaccess

- modules/admin_manual/pages/useful_pages.adoc
- modules/admin_manual/partials/nav.adoc
When cleaning up the main [docs page](https://github.com/owncloud/docs/pull/4800), the following content was not appropriate located anymore and is now moved to the server. It got an own page. Beside the headlines it is contenwise 1:1
> Create a Useful Pages page

- modules/admin_manual/pages/installation/apps_supported.adoc
References: #795 (Adding Additional Enterprise Apps)
* OIDC is not an enterprise app
* completing links where available
> Update apps supported

- modules/admin_manual/examples/installation/manual_installation/owncloud_prep.sh
Fixes: #809 ([QA] instance.sh suggests to run occ upgrade while still in maintenance mode)
The suggested order of commands that have to be typed manually post the script run needed to be resorted.
@jnweiger fyi
> Fixing the sort order of suggested commands in owncloud_prep.sh

- modules/admin_manual/pages/configuration/user/oidc/ms-azure-setup.adoc
- modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
You can build branded desktop and mobile clients for Azure AD. I'd like to add this to the docs.
Ho to test:
```
git clone https://github.com/owncloud/docs-server.git
cd docs-server
git checkout azure-branded-clients
yarn install
yarn antora
yarn serve
```
Preview:
- http://127.0.0.1:8080/server/next/admin_manual/configuration/user/oidc/oidc.html#example-setup-using-microsoft-azure-ad
- http://127.0.0.1:8080/server/next/admin_manual/configuration/user/oidc/ms-azure-setup.html#register-owncloud-desktop-and-mobile-clients
> [OIDC] Branded desktop and mobile clients for Azure AD

- modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_ransomware_protection_commands.adoc
- modules/admin_manual/pages/enterprise/security/ransomware-protection/index.adoc
Fixes: #805 (New occ functionality for the ransomware app)
Also see the references in the issue to the code for details.
* restructure the ransomware occ page
* adding new occ ransomware commands
* updating the table in the ransomware documentation
@jvillafanez @jnweiger fyi
> New occ ransomware command

- modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_maintenance_commands.adoc
Changed `maintenance:repair` --> `maintenance:mode` since it wasn't listed correctly.
> wrong command named

- modules/admin_manual/pages/configuration/user/login_policies.adoc
- modules/admin_manual/partials/nav.adoc
Fixes: https://github.com/owncloud/docs-server/issues/796 (Documentation of new functionality: Add support for login policies)
No backports, this is for the upcoming release of core (10.12)
@jnweiger @jvillafanez FYI
> Add Login Policies

- modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
References: https://github.com/owncloud/core/pull/40613 ([docs-only] Fix auto-provision in config.apps.sample)
Fixes for config.apps.sample (oidc auto-provision)
> Config-to-Docs run for changes in Core (oidc auto-provision)

- antora.yml
Fixes: #661 (PHP 7.3 support will get dropped - needs documentation)
Update the minimum required PHP version to 7.4.
Locally tested, looks fine.
No backport !
> Update PHP minimum version

- modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_sharing_commands.adoc
Fixes: #837 (New occ config app key for files_sharing)
A new app config key has been added to allow to temporarily ignore invalid federated shares.
No backport, part of the next release.
> occ: Allow to Temporarily Ignore Invalid Federated Shares

- modules/admin_manual/pages/configuration/database/linux_database_configuration.adoc
Fixes: #838 (mysql innodb file format config change on mysqld is only necessary on 5.7)
Improve the text and its visability via a NOTE to make it more clear when to use necessary commands and when not.
> Update Configure MySQL for 4-byte Unicode Support

- modules/admin_manual/pages/configuration/files/manual_file_locking.adoc
Technically, we are prone to a race condition, as we first have to unlock and then write. But that is how a webdav lock works. See discussion in https://github.com/owncloud/core/issues/40637 and https://github.com/owncloud/core/issues/40637
> Explain check-out, check-in by example.

- modules/ROOT/pages/index.adoc
Should the entry page of the server guide only address admins and devs? I'd assume there are at least as many end users who end up here...
> Also mention user guide?

- modules/admin_manual/pages/installation/manual_installation/manual_imagick7.adoc
@mmattel, here is the short addition I was talking about. I'm not sure if we should explain that further of if this is sufficient.
Maybe it makes sense to add this also to the "Important" block here: https://doc.owncloud.com/server/10.11/admin_manual/configuration/files/previews_configuration.html#introduction?
> add notice about ImageMagick's scripting language (MSL)

- modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_user_commands.adoc
Fixes: #853 (Backend class alias on user:sync)
Backend classes can now have a short form.
No backport
> user:sync short form of backend classes

- docs/new-version-branch.md
This is just a small text update for the new version branch documentation.
No backport needed.
> Update the new version branch documentation

- modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
Fixes: #858 (Default value of concurrency should be 3, not 5) and #859 (Description of concurrency)
Backport to 10.10, 10.11 and 10.12
> Update S3 concurrency example

- modules/admin_manual/pages/configuration/general_topics/search.adoc
Fixes: #865 ([QA] elastic search updates) and #864 (QA] docs claim that search_elastic works with encryption)
Updates the search description.
Backport to 10.12, 10.11 and 10.10
> Update the search app

- modules/admin_manual/pages/installation/quick_guides/ubuntu_22_04.adoc
because if not, bash leaves it empty
Backport to 10.10, 10.11 and 10.12
> escape variable

- modules/admin_manual/pages/installation/quick_guides/ubuntu_22_04.adoc
testing at this point prevents further debugging at a later point in the setup.
please rewrite the text and formatting as you see fit.
maybe this is also not the most elegant solution for fixing the warning message when you reboot apache, but this solution works.
I know that if you use this script more than once the end of your apache2 conf gets messy at the bottom.
Backport to 10.10, 10.11 and 10.12
> add testing of apache config

- modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_ldap_integration_commands.adoc
`ldapNetworkTimeout` key when using the `ldap:set-config` occ command
https://doc.owncloud.com/server/next/admin_manual/configuration/server/occ_command.html#manipulate-ldap-configurations
Currently this key is not documented.
@mmattel as discussed. Documented default value to 15secs as next user_ldap version (0.17.0) will set default to this value. See https://github.com/owncloud/user_ldap/pull/734.
Backport to 10.10, 10.11 and 10.12
> Document ldapNetworkTimeout

- modules/admin_manual/pages/configuration/files/file_versioning.adoc
References: #899
The table definition was accidentially broken - fixed.
Backport to 10.12
> Fix file_versions table

- modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
References: https://github.com/owncloud/core/pull/40688 (chore: remove unused openidconnect config option `use-token-introspection-endpoint`)
The config setting has been removed from the docs,
it was never functional in the openidconnect app.
Backport to 10.12 and 10.11
> Config to docs run based on recent changes from core

- modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
I was too fast. the change was discussed and considered to risky for a patchlevel release.
This encryption-1.6.0 update will occur with 10.13.xx while 10.12.1 will keep encryption-1.5.3
> no encryption update in 10.12.1

- modules/developer_manual/pages/testing/ui-testing.adoc
seems to fix #924 for me. At least
With these changes, one test that I tried now passes:
```
When the administrator sets the following email server settings using the webUI                    # WebUIAdminGeneralSettingsContext::administratorSetsTheFollowingSettingsInEmailServerSettingUsingTheWebui()
| setting                 | value        |
| send mode               | smtp         |
| encryption              | None         |
| from address            | owncloud     |
| mail domain             | foobar.com   |
| authentication method   | None         |
| authentication required | false        |
| server address          | %EMAIL_HOST% |
| port                    | 2500         |
â INFORMATION: timed out waiting for ajax calls to start
And the administrator clicks on send test email in the …
```
> ui-testing.adoc - deprecate mailhog in favoir of inbucket

- modules/admin_manual/pages/installation/manual_installation/manual_installation_prerequisites.adoc
Added an example to to implement the fix required for current LTS version of Ubuntu (22.04) and ownCloud encryption.
relevant docs page: 
https://doc.owncloud.com/server/next/admin_manual/installation/manual_installation/manual_installation_prerequisites.html#openssl-version
it's in the "important" block.
please add the docs magic to it so it looks nice. The commands should be in code blocks, but I did not know how to do them right.
I am aware that this example might become outdated in the future, but without it many users and or admins might get lost on what to implement where and how. This should act as a example. 
I also added an anchor for the relevant section of the ssl docs.
> added instructions how to enable legacy support

- modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_22.04.adoc
Encountered php-warnings and ``pear upgrade [...]`` wasn't working until I changed the primary PHP version to 7.4.
Logs from multipass: [https://pastebin.com/RWvQUp4r](https://pastebin.com/RWvQUp4r)
> Changed order of pear & php-alternatives

- modules/admin_manual/pages/installation/letsencrypt/apache.adoc
https://doc.owncloud.com/server/next/admin_manual/installation/letsencrypt/apache.html
This docs was missing the ssl mode enabling part, so I added it. Without it the ssl configuration fails.
> added enabling of ssl module to apache ssl configuration

- modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
Preview role for public links does not exist yet. Will likely be implemented in 10.13.0. References to it should be removed from the 10.11 documentation. "Next" can stay.
> Update collabora_secure_view.adoc [10.11.0]

- modules/admin_manual/pages/installation/letsencrypt/apache.adoc
If we provide a apache documentation here: https://doc.owncloud.com/server/next/admin_manual/installation/letsencrypt/apache.html then it's missing the important last step to redirect all http traffic to https.
This PR adds the instructions at the end of the page.
> added redirect permanent configuration

- modules/admin_manual/pages/installation/system_requirements.adoc
Fixes #962 
oC10 works with recent MariaDB releases 10.9 10.10 and 10.11 - see core issue https://github.com/owncloud/core/issues/40762 -  Update the docs to say this.
I could only find this one place to change. All other mentions of MariaDB in the docs do not need to change.
After running the core tests linked from core issue https://github.com/owncloud/core/issues/40762 I am confident that there is no problem using these newer MariaDB releases, so we may as well document that.
It will work fine with any oC10 core release from 10.9 onward. (oC10.9 provided support for a change that happened in MariaDB 10.6). So backport this docs change to oC core 10.12 and 10.11 docs branches.
> Expand MariaDB support up to 10.11

- modules/admin_manual/pages/enterprise/reporting/metrics.adoc
Fixes: https://github.com/owncloud/metrics/issues/170 ([QA] Data format of metrics/api/v1/metrics changed)
We now mention new the fields usedQuota and usedOther --  maybe that is a bit to much, as all other fields are not explicitly mentioned with their exact names...
If you ask me, it does not harm :-)
> Update metrics.adoc for PR #166

- modules/admin_manual/pages/configuration/files/mimetypes.adoc
my IDE tells me that a trailing comma is not valid in JSON.
So I think that these example responses need the trailing comma removed.
Backport to 10.12 and 10.11
> Remove trailing comma in JSON

- site.yml
We have updated `site.yml` in the docs repo but missed to do this here too.
It had no negative effect as the main build runs via the docs repo but local building throws a warning about missing attributes.
Note that there will be a CI error that has nothing to do with the PR, I am currently investigating.
> Add missing attributes in site.yml (local build relevant only)

- modules/admin_manual/pages/configuration/files/external_storage/configuration.adoc
References: #978 (Add occ files:remove-storage command)
Fixed the text as an occ command was added. Found "accidentially" while working on an other topic.
No backport, master only
> Update configuration.adoc (how to remove orphand storage entries))

- modules/admin_manual/pages/installation/system_requirements.adoc
Fixes: #1016 (System Requirements page update)
Update MariaDB to 10.11
> Update system_requirements, use MariaDB 10.11 as default

- modules/admin_manual/pages/configuration/server/email_configuration.adoc
This setting goes in the array that is defined in `config.php`
It should end in a comma.
Can be backported to all supported doc branches.
> Fix syntax of mail_smtpdebug example

- modules/admin_manual/pages/configuration/server/email_configuration.adoc
> [10.12] [PR 1030] Fix syntax of mail_smtpdebug example

- modules/admin_manual/pages/maintenance/migrating.adoc
We have this link embedded in the trusted domains error message: https://doc.owncloud.com/server/10.12/go.php?to=admin-untrusted-domain it seems to end up in the migration.html page. Maybe there is other/better places, that already describe trusted domains issues in more detail? 
I just want to dump these hints somewhere, as this is probably, how we can get the appliance to behave.
My markdown syntax is probably completely wrong, and this should of course not only go to 10.12, but also to master. Sorry.
> Added some hints how to survive the trusted_domains issue with docker

- modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_data_exporter_commands.adoc
- modules/admin_manual/pages/maintenance/export_import_instance_data.adoc
See https://github.com/owncloud/data_exporter/issues/234 and https://github.com/owncloud/data_exporter/pull/236
The 1st commit tidies up some existing things in the data_exporter docs.
The 2nd commit adds the note about last login timestamp.
> Document data exporter 236 last login timestamp behavior

- modules/admin_manual/pages/configuration/server/occ_command.adoc
However this slipped thru... ?
Fixes an import statement for an occ command - the include name was not identical to the filename.
> Fix import name of occ cammand

- modules/admin_manual/examples/installation/docker/docker-compose.yml
- modules/admin_manual/pages/installation/docker/index.adoc
Fixes: https://github.com/owncloud/docs-server/issues/1067 (Installation instructions broken)
* The docker compose example section needed a fix.
* The broken link in the referenced issue is on the homepage and needs fixing there
will initiate the fix
@jnweiger fyi
> Update the Docker Compose section

- modules/admin_manual/pages/installation/docker/index.adoc
The path should not magically change.
> Avoid Fairydust

- modules/admin_manual/pages/configuration/server/occ_command.adoc
- modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_federation_trusted_servers.adoc
Fixes: #1088 (New occ command for 10.13: federation:trusted-servers:add)
Adds the new `occ federation:trusted-servers` command set introduced with 10.13
Backport to 10.13
@jnweiger FYI
> Add new occ federation:trusted-servers

- modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
- modules/admin_manual/pages/installation/quick_guides/ubuntu_22_04.adoc
- modules/admin_manual/partials/installation/manual_installation/mariadb.adoc
- modules/admin_manual/partials/nav.adoc
Fixes: #1061 (Installation guide: Database: Grant privileges + create user no longer works on mysql)
* use the correct SQL command in the quick guides
* fix commands in the detailed guide 
* improve nav for better readbility (link stays the same)
* some other small fixes
> Fix SQL commands when installing

- modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
This typo was accidentally introduced in PR #1106
> Fix typo in federated_cloud_sharing_configuration.adoc

- modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
Fixes: https://github.com/owncloud/docs/issues/4883
Page aliases did not work. Newline between page attributes was removed. While asciidoc does not care about newlines between custom attributes like `hackerone-url` for Antora page attributes, this did not work. 
> Fix encryption configuration page aliases

- modules/admin_manual/pages/enterprise/authentication/enterprise_only_auth.adoc
- modules/admin_manual/pages/enterprise/clients/creating_branded_apps.adoc
- modules/admin_manual/pages/enterprise/clients/index.adoc
- modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
- modules/admin_manual/pages/enterprise/collaboration/index.adoc
- modules/admin_manual/pages/enterprise/document_classification/classification_and_policy_enforcement.adoc
- modules/admin_manual/pages/enterprise/document_classification/index.adoc
- modules/admin_manual/pages/enterprise/external_storage/index.adoc
- modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
- modules/admin_manual/pages/enterprise/file_management/files_tagging.adoc
- modules/admin_manual/pages/enterprise/file_management/index.adoc
- modules/admin_manual/pages/enterprise/firewall/file_firewall.adoc
- modules/admin_manual/pages/enterprise/firewall/index.adoc
- modules/admin_manual/pages/enterprise/index.adoc
- modules/admin_manual/pages/enterprise/logging/admin_audit.adoc
- modules/admin_manual/pages/enterprise/logging/index.adoc
- modules/admin_manual/pages/enterprise/reporting/index.adoc
- modules/admin_manual/pages/enterprise/reporting/metrics.adoc
- modules/admin_manual/pages/enterprise/security/index.adoc
- modules/admin_manual/pages/enterprise/security/ransomware-protection.adoc
- modules/admin_manual/pages/enterprise/server_branding/enterprise_server_branding.adoc
- modules/admin_manual/pages/enterprise/server_branding/index.adoc
- modules/admin_manual/pages/enterprise/user_management/index.adoc
- modules/admin_manual/pages/enterprise/user_management/saml_2.0_sso.adoc
- modules/admin_manual/partials/nav.adoc
This PR removes all index.adoc pages from the enterprise section which were just telling "you are here".
A redirect as been added to a page part of each sub section to avoid a 404.
Necessary as preperation for the enterprise/kerberos documentation, see issue #1098.
> Remove all senseless index.adoc pages from the enterprise section

- modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
When updating ownCloud, there is the need to update permissions on directories.
This PR fixes that all app directories are catched.
@voroyam fyi (and thanks for catching)
> Catch all app directories for updating permissions

- modules/admin_manual/pages/configuration/index.adoc
- modules/admin_manual/pages/troubleshooting/index.adoc
- modules/admin_manual/partials/nav.adoc
Fixes #1138 (Loop in the next -> next -> next ... chain)
This PR removes meaningless index pages to nav headings as we have in other main nav entries.
> Remove meaningless index pages from the admin navigation

- package.json
- yarn.lock
Backport of PR #1143
Necessary for local builds only.
> [10.13] [PR 1143] Bump @asciidoctor/core from 2.2.6 to 3.0.2

- package.json
- yarn.lock
Backport of PR #1143
Necessary for local builds only.
> [10.12] [PR 1143] Bump @asciidoctor/core from 2.2.6 to 3.0.2

- modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
for a support case we tested the ldaps configuration in ownCloud, which depends on the certificate you import from the windows server, you have to import the right one in the right format, then change the format and place it in the right place on the ownCloud server, in the ldap client directory, and specify in the configuration that the client should use exactly that certificate.
we need also a warning or a note that the protocol has to be entered and can not be omitted with ldaps, you have to add ldaps:// to the host name of your ldap server. We have this as a note in the webUI but the not is very small and easy to overlook. I overlooked it, the customer did as well. Not a good solution. 
I added the steps for centOS. I know this is a ubuntu only doc, but we have many customers who have …
> added compelte ldaps doc, step by step

- modules/admin_manual/pages/appliance/installation/installation.adoc
I have no Idea, what problem the paragraph about removing DNS entries wants to solve. Suggest to drop that paragraph.
Instead, and much more important, we should recommend bridged mode. 
(I was testing with NAT and port forwarding today, but ran in all sorts of errors: the UCS 5 dashboard drops port numbers while redirecting, the internal DNS of UCS produces wrong mappings. etc..)
> Update appliance installation.adoc

- modules/admin_manual/pages/appliance/configuration/firewall.adoc
owncloud.org can be safely removed, we no longer use that domain.
176.9.114.147 has an invalid self singned certificate. It seem to be a hetzner machine. Without specifying a very good reason we should not ask anybody to trust this machine. I have no idea, by whom it is operated.
5.9.68.237 has a cert that identifies as "int.owncloud.com"; most likely it is also obsolete.
> Update appliance firewall.adoc

- modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
- modules/admin_manual/pages/installation/docker/index.adoc
Supercedes: #1184 (Update docs pertaining to the use of 'OWNCLOUD_TRUSTED_DOMAINS') 
* Update config.sample file via a `config-to-docs` run
* Update the docker description
> Updates config.sample and some docker related text

- modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
References: https://github.com/owncloud/core/pull/41106 (docs: clarify missing wnd config parameter)
Got a late info about a missing parameter description.
> Another necessary config to docs run

- modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
On request of @voroyam to improve customer experience 😄 
Backport to 10.12 and 10.13
> Fix download link address for upgrades to be the same as in wget command below

- modules/admin_manual/pages/installation/apps_supported.adoc
These xrefs have been identified to cause errors and needed a fix.
> Fix faulty xrefs found during the antora upgrade

- modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
- modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
- modules/admin_manual/pages/configuration/user/custom_groups_app.adoc
- modules/admin_manual/pages/maintenance/upgrading/package_upgrade.adoc
- modules/admin_manual/pages/maintenance/upgrading/update.adoc
- modules/admin_manual/pages/maintenance/upgrading/upgrade.adoc
- modules/admin_manual/pages/qnap/index.adoc
Fix needed to get rid of xref errors because of upgrading to Antora 3.
Make them absolute references and no longer xrefs. Do not want to wait for the availability of Antora Atlas which would fix the issue.
> Fix links mostly to the server release notes

- modules/admin_manual/pages/configuration/server/email_configuration.adoc
The app templateeditor is dropped. All editing of templates should be done in a custom theme.
See https://github.com/owncloud/templateeditor/issues/154
> remove references to templateeditor in email_configuration.adoc

- modules/admin_manual/pages/configuration/files/previews_configuration.adoc
Hinting at enabled imagic is not sufficient. imagic may or may not have builtin support for all of these. E.g.: Currently our docker image have an imagick that neither supports SVG nor PDF.
Compare https://github.com/owncloud/core/issues/41185
> Update previews_configuration.adoc - PreviewProvider clarification

- .drone.star
These are the changes necessary to finalize the creation of the 10.14 branch.
* The 10.14 branch is already pushed and prepared and is included in the branch protection rules.
* When 10.14 (core) is finally out, the 10.12 branch can be archived, see step 3 in [Create a New Version Branch](https://github.com/owncloud/docs-server/blob/master/docs/new-version-branch.md)
* Note, that the 10.14 branch in this repo is already created, but the `latest` pointer on the web will be set to it automatically when the tag in core is set. This means, that in the docs homepage, `latest` will point to 10.13 until the tag in core is set accordingly. When merging this PR, 10.12 will be dropped from the web.
* Note that this PR must be merged **before** the 10.14 tag in core is set to avoid a 404 for …
> Changes necessary for the 10.14 branch

- modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
- modules/admin_manual/pages/configuration/files/encryption/encryption_configuration_quick_guide.adoc
- modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_encryption_commands.adoc
- modules/admin_manual/pages/configuration/server/security/hsmdaemon/index.adoc
- modules/admin_manual/pages/maintenance/encryption/migrating-from-user-key-to-master-key.adoc
Only master-key is supported now so the command is not available anymore.
Related Change: https://github.com/owncloud/encryption/pull/389
Backport to 10.14 and 10.13
> fix: select encryption type is obsolete

- modules/developer_manual/pages/core/apis/ocs-share-api.adoc
It is unclear, if only the listed numbers are supported. I'd think, that 1+2+4+8+16 are meant as bit patters that can be combined as needed. 15, 31 are probably just examples.
What does 'default for public link shares' mean? Is the 1 bit always added for these? I don't think so, as this would prevent building an anonymous file drop link.
See https://central.owncloud.org/t/share-files-via-api-without-delete-permissions/49350
> clarify sharing bits

- modules/developer_manual/examples/scripts/backport.sh
This PR updates the backport script to allow empty cherry picks.
Tested locally, works as expected.
Backport to 10.14
> Update the backport script to allow empty cherry picks

- modules/admin_manual/pages/maintenance/manually-moving-data-folders.adoc
Previously, files would be moved to data/user/files/files, which is fixed with this step.
The brief was also rewritten for clarity, so others don't make the same mistakes I did.
> Clarify and correct accounts table step

- modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Fixes: #1347 ([QA] configreport new feature needs documentation: telemetry)
Adds changes from core into config.sample via a config to docs run.
Renders fine locally.
Backport to 10.15
Only merge if the referenced core PR from the issue is merged.
> Config to docs run based on recent config sample changes

- modules/developer_manual/pages/core/apis/ocs-share-api.adoc
- modules/developer_manual/pages/general/codingguidelines.adoc
Found while testing fixing `package.json` for updating proper installation of antora (our way is outdated).
There are table warnings that tables were not correctly defined - this is fixed now.
Backporting to 10.15, 10.14 and 10.13 necessary
> Fix two build error messages in dev docs

- modules/admin_manual/pages/configuration/server/security/oauth2.adoc
The effect of token_auth_enforced is officially described in the sample config php. There it is only discussed in the context of basic auth vs. app tokens. 
Admins migrating from basic auth to oauth2 may eventually come here, and wonder what exact effect token_auth_enforced has. oauth2 either way, true or false, but true does not do a hard enforce.
> clarify token_auth_enforced in oauth2.adoc

- modules/admin_manual/pages/enterprise/authentication/kerberos.adoc
The current installation description will install all `php-dev` packages. So on newer systems this will install a complete php 8 stack as well even if there was only php 7.4 installed so far. So the description should be change to install the dev package of the appropriate version.
> Change php-dev version used for Kerberos

- modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_data_exporter_commands.adoc
Found while working on the KW migration occ documentation, the description was not complete - fixed.
> Fix data exporter occ command description

- modules/admin_manual/pages/configuration/server/occ_command.adoc
- modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_migrate_to_kitworks_commands.adoc
- modules/admin_manual/pages/maintenance/migrating_to_kiteworks.adoc
Fixes: #1319 (Improvements to kiteworks migration guide)
Supersedes: #1362 (fix: migration is now split into sub commands)
Fixes the migration documentation based on the referenced issue.
Currently visible on [staging](https://doc.staging.owncloud.com/server/next/admin_manual/maintenance/migrating_to_kiteworks.html).
> Update Kiteworks migration documentation

- modules/admin_manual/pages/maintenance/migrating_to_kiteworks.adoc
I wasn't aware that codenames are internal use only. Sorry.
> Codename Zion is internal. Use 8.6 instead

- modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
For ADFS, client-secrets must not contain an underscore because ADFS does not support this.
Backport to 10.14 and 10.15
> Add OIDC-ADFS client secret restriction

- modules/developer_manual/pages/webdav_api/search/_search_files.adoc
Fixes: #1394 (Wrong code example for 'filter-rules')
Easy fix 😄 
> Fix including wrong filter example

- ext-antora/find-orphaned-files.js
- false-positives.txt
- site.yml
This extension, if enabled, will report all files that are orphaned in the modules directory.
Note that because of the algorythm used, orphaned files may be still valid.
For a detailed description and how to use it see: [Useful Antora and Asciidoc Extensions](https://github.com/mmattel/Antora-Asciidoc-Extensions).
Note that this PR just adds the extension, it does not remove any orphaned files. This will be done in an additional PR.
Backport is not needed.
> Add Find Orphaned Files Antora extension

- modules/admin_manual/pages/configuration/server/security/dependency_notes.adoc
- modules/admin_manual/partials/nav.adoc
The original page and url name is misleading now as it originally focused on jquery only.
Now we have added apps, which are not jquery related, the page name and headline got updated.
The text also got revised.
> Restructure dependency warnings/notes

- modules/admin_manual/pages/configuration/server/security/dependency_notes.adoc
There is no vulnerability for CVE-2024-6485 and CVE-2024-6484
> Add no vulnerability for two bootstrap CVE's

- modules/admin_manual/pages/configuration/integration/ms-teams.adoc
- modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_config_reports_commands.adoc
- modules/admin_manual/pages/installation/system_requirements.adoc
References: https://github.com/owncloud/docs-main/pull/101 (Remove or adapt support and survey links)
This PR finalizes the removal / adaption of support links. No survey links have been found.
> Remove or adapt support links

- modules/admin_manual/pages/maintenance/migrating_to_kiteworks.adoc
Fixing:
* `Private Content Network` --> `Private Data Network`
* `PCN` --> `PDN`
Backport to 10.14 and 10.15
> Update Kitweworks wording in migration

- modules/admin_manual/pages/configuration/server/harden_server.adoc
- modules/admin_manual/pages/installation/manual_installation/manual_installation_db.adoc
- modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
- modules/admin_manual/pages/installation/quick_guides/ubuntu_22_04.adoc
Add the `STRICT_TRANS_TABLES` mode to the DB installation for MariaDB/MySQL.
Locally tested on my instance, works.
> Add STRICT_TRANS_TABLES to MariaDB/MySQL

- modules/admin_manual/partials/nav.adoc
Fixes a naming leftover `PCN` --> `PDN`
> Fix PCN to PDN leftover

- modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
References:  #1471 (Config to Docs run: Remove the web-updater)
An error sneaked in via the referenced PR, this is the correction for the removal.
Backport to 10.15
> Config to Docs run: Remove the web-updater (II)
