owncloud/docs-server

modules/admin_manual/pages/configuration/search/index.adoc
Sync 10.9 content from docs
No Backport
=> sync 10.9 content from docs

site.yml
Fixes site.yml for the upcoming phaseout from docs
=> fixes site.yml

site.yml
=> [10.8] [PR 10] fixes site.yml

site.yml
=> [10.9] [PR 13] Add page-component-build-list to site.yml

site.yml
=> [10.8] [PR 13] Add page-component-build-list to site.yml

docs/the-branching-workflow.md, modules/admin_manual/pages/index.adoc, modules/no_man/pages/index.adoc, modules/no_man/partials/nav.adoc, modules/no_man/readme.md
This PR prepares the repo to give access to content in the ROOT module.
For details read `modules/no_man/readme.md`
In addition, some small fixes have been added.
=> Prepare access from outside to the ROOT module

docs/the-branching-workflow.md, modules/admin_manual/pages/index.adoc, modules/no_man/pages/index.adoc, modules/no_man/partials/nav.adoc, modules/no_man/readme.md
=> [10.9] [PR 22] Prepare access from outside to the ROOT module

docs/the-branching-workflow.md, modules/admin_manual/pages/index.adoc, modules/no_man/pages/index.adoc, modules/no_man/partials/nav.adoc, modules/no_man/readme.md
=> [10.8] [PR 22] Prepare access from outside to the ROOT module

modules/admin_manual/pages/installation/manual_installation/manual_installation_apache.adoc, modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc, modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc, site.yml
=> [10.9] [PR 30] mpm_event conflicts with php

modules/admin_manual/pages/installation/manual_installation/manual_installation_apache.adoc, modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc, modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc, site.yml
=> [10.8] [PR 30] mpm_event conflicts with php

modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
=> [10.9] [PR 34] Config-to-docs Run

modules/admin_manual/pages/troubleshooting/remove_non_existent_bg_jobs.adoc
Correction line 62, not "status" for delete but "delete"
Backport #36
=> [10.9] Update remove_non_existent_bg_jobs.adoc

modules/admin_manual/pages/installation/docker/index.adoc
=> [10.9] [PR 41] Fix docker compose example link

modules/admin_manual/pages/installation/docker/index.adoc
=> [10.8] [PR 41] Fix docker compose example link

antora.yml, modules/ROOT/pages/index.adoc, modules/ROOT/partials/nav.adoc, modules/admin_manual/pages/index.adoc, modules/developer_manual/pages/index.adoc
=> [10.9] [PR 44] Update naming

modules/ROOT/pages/index.adoc
=> [10.8] [PR 47] Fix the resource coordinates in the introduction

antora.yml
This sneaked in with a backport 🤦‍♂️ 
NO Backport
=> [10.8] only - fix version in antora.yml

modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
=> [master] [PR 50] Remove mistake entry about incompatibility with storage encryption

modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc, modules/admin_manual/pages/configuration/files/encryption/encryption_configuration_quick_guide.adoc, modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc, modules/admin_manual/pages/maintenance/upgrading/package_upgrade.adoc, modules/admin_manual/pages/maintenance/upgrading/update.adoc, modules/admin_manual/pages/maintenance/upgrading/upgrade.adoc, site.yml
=> [10.8] [PR 54] Fix broken antora component links to docs

modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc, modules/admin_manual/pages/configuration/files/encryption/encryption_configuration_quick_guide.adoc, modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc, modules/admin_manual/pages/maintenance/upgrading/package_upgrade.adoc, modules/admin_manual/pages/maintenance/upgrading/update.adoc, modules/admin_manual/pages/maintenance/upgrading/upgrade.adoc, site.yml
=> [10.9] [PR 54] Fix broken antora component links to docs

modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
=> [10.9] [PR 60] Update ubuntu_20_04.adoc

modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
=> [10.8] [PR 60] Update ubuntu_20_04.adoc

modules/admin_manual/examples/installation/manual_installation/owncloud_prep.sh, modules/admin_manual/pages/installation/manual_installation/manual_installation.adoc, modules/admin_manual/pages/installation/manual_installation/script_guided_install.adoc, modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc, site.yml
=> [10.8] [PR 59] Update manual upgrade documentation

modules/admin_manual/examples/installation/manual_installation/owncloud_prep.sh, modules/admin_manual/pages/installation/manual_installation/manual_installation.adoc, modules/admin_manual/pages/installation/manual_installation/script_guided_install.adoc, modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc, site.yml
=> [10.9] [PR 59] Update manual upgrade documentation

modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
=> [10.9] [PR 65] Fix complete bundle name

modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
=> [10.8] [PR 65] Fix complete bundle name

modules/developer_manual/pages/app/advanced/extstorage.adoc, modules/developer_manual/pages/app/advanced/notifications.adoc, modules/developer_manual/pages/app/fundamentals/backgroundjobs.adoc, modules/developer_manual/pages/app/fundamentals/database.adoc, modules/developer_manual/pages/app/fundamentals/filesystem.adoc, modules/developer_manual/pages/core/apis/ocs-capabilities.adoc, modules/developer_manual/pages/core/apis/ocs-notification-endpoint-v1.adoc, modules/developer_manual/pages/core/apis/ocs-notify-public-link-by-email.adoc, modules/developer_manual/pages/core/apis/ocs-recipient-api.adoc, modules/developer_manual/pages/core/apis/ocs-share-api.adoc, modules/developer_manual/pages/core/apis/ocs-totp-validation-api.adoc, modules/developer_manual/pages/core/apis/ocs-user-sync-api.adoc, modules/developer_manual/pages/core/apis/roles-api.adoc, modules/developer_manual/pages/core/theming.adoc, modules/developer_manual/pages/general/backporting.adoc, modules/developer_manual/pages/testing/acceptance-tests.adoc, modules/developer_manual/pages/testing/unit-testing.adoc, modules/developer_manual/pages/webdav_api/groups/custom_groups_endpoints.adoc, modules/developer_manual/pages/webdav_api/groups/group_membership_endpoints.adoc, modules/developer_manual/pages/webdav_api/meta.adoc, modules/developer_manual/pages/webdav_api/public_files.adoc, modules/developer_manual/pages/webdav_api/search/_filter_files.adoc, modules/developer_manual/pages/webdav_api/search/_search_files.adoc, modules/developer_manual/pages/webdav_api/trashbin.adoc, modules/developer_manual/partials/webdav_api/files_versions/list_files_versions.adoc, modules/developer_manual/partials/webdav_api/search/common_error_responses.adoc
=> [10.9] [PR 69] Dev: rename {examplesdir} with example$

modules/developer_manual/pages/app/advanced/extstorage.adoc, modules/developer_manual/pages/app/advanced/notifications.adoc, modules/developer_manual/pages/app/fundamentals/backgroundjobs.adoc, modules/developer_manual/pages/app/fundamentals/database.adoc, modules/developer_manual/pages/app/fundamentals/filesystem.adoc, modules/developer_manual/pages/core/apis/ocs-capabilities.adoc, modules/developer_manual/pages/core/apis/ocs-notification-endpoint-v1.adoc, modules/developer_manual/pages/core/apis/ocs-notify-public-link-by-email.adoc, modules/developer_manual/pages/core/apis/ocs-recipient-api.adoc, modules/developer_manual/pages/core/apis/ocs-share-api.adoc, modules/developer_manual/pages/core/apis/ocs-totp-validation-api.adoc, modules/developer_manual/pages/core/apis/ocs-user-sync-api.adoc, modules/developer_manual/pages/core/apis/roles-api.adoc, modules/developer_manual/pages/core/theming.adoc, modules/developer_manual/pages/general/backporting.adoc, modules/developer_manual/pages/testing/acceptance-tests.adoc, modules/developer_manual/pages/testing/unit-testing.adoc, modules/developer_manual/pages/webdav_api/groups/custom_groups_endpoints.adoc, modules/developer_manual/pages/webdav_api/groups/group_membership_endpoints.adoc, modules/developer_manual/pages/webdav_api/meta.adoc, modules/developer_manual/pages/webdav_api/public_files.adoc, modules/developer_manual/pages/webdav_api/search/_filter_files.adoc, modules/developer_manual/pages/webdav_api/search/_search_files.adoc, modules/developer_manual/pages/webdav_api/trashbin.adoc, modules/developer_manual/partials/webdav_api/files_versions/list_files_versions.adoc, modules/developer_manual/partials/webdav_api/search/common_error_responses.adoc
=> [10.8] [PR 69] Dev: rename {examplesdir} with example$

modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc, modules/admin_manual/pages/enterprise/user_management/user_auth_shibboleth.adoc, modules/admin_manual/pages/installation/apps_management_installation.adoc, modules/admin_manual/pages/installation/deployment_recommendations.adoc, modules/admin_manual/pages/installation/docker/index.adoc, modules/admin_manual/pages/installation/letsencrypt/using_letsencrypt.adoc, modules/admin_manual/pages/installation/manual_installation/manual_installation_apache.adoc, modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
=> [10.9] [PR 70] Admin: rename {examplesdir} with example$

modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc, modules/admin_manual/pages/enterprise/user_management/user_auth_shibboleth.adoc, modules/admin_manual/pages/installation/apps_management_installation.adoc, modules/admin_manual/pages/installation/deployment_recommendations.adoc, modules/admin_manual/pages/installation/docker/index.adoc, modules/admin_manual/pages/installation/letsencrypt/using_letsencrypt.adoc, modules/admin_manual/pages/installation/manual_installation/manual_installation_apache.adoc, modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
=> [10.8] [PR 70] Admin: rename {examplesdir} with example$

modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc, modules/admin_manual/pages/enterprise/external_storage/wnd_quick_guide.adoc, modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc, modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
This PR removes the ondrej remnant in WND and fixes some WND text stuff.
Additionally, not necessary linebreaks in corresponding files have been removed which have no impact on the build but make the source better to read and to edit.
=> Remove ondrej remnants and fix WND

modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc, modules/admin_manual/pages/enterprise/external_storage/wnd_quick_guide.adoc, modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc, modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
=> [10.8] [PR 76] Remove ondrej remnants and fix WND

modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc, modules/admin_manual/pages/enterprise/external_storage/wnd_quick_guide.adoc, modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc, modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
=> [10.9] [PR 76] Remove ondrej remnants and fix WND

modules/developer_manual/pages/app/fundamentals/info.adoc, modules/developer_manual/pages/core/apis/index.adoc, modules/developer_manual/pages/testing/index.adoc, modules/developer_manual/pages/webdav_api/files_versions.adoc, modules/developer_manual/pages/webdav_api/groups/custom_groups_endpoints.adoc, modules/developer_manual/pages/webdav_api/groups/group_membership_endpoints.adoc, modules/developer_manual/pages/webdav_api/index.adoc, modules/developer_manual/pages/webdav_api/meta.adoc, modules/developer_manual/pages/webdav_api/search/_filter_files.adoc, modules/developer_manual/pages/webdav_api/search/_search_files.adoc
=> [10.9] [PR 81] Dev: rename {partialsdir} with partial$

modules/admin_manual/partials/nav.adoc
=> [10.9] [PR 90] Shift the wizard location by one to the left

modules/admin_manual/partials/nav.adoc
=> [10.8] [PR 90] Shift the wizard location by one to the left

modules/admin_manual/pages/installation/index.adoc
The main installation overview needed an urgent improvement reflecting the recent changes made.
=> Fix the main installation overview document

modules/admin_manual/pages/installation/index.adoc
=> [10.8] [PR 98] Fix the main installation overview document

modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
=> [10.9] [PR 75] Update ubuntu_20_04.adoc

modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
=> [10.8] [PR 75] Update ubuntu_20_04.adoc

modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
=> [10.8] [PR 106] Update manual_upgrade.adoc

modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
=> [10.9] [PR 106] Update manual_upgrade.adoc

modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
=> [10.8] [PR 113] Ubuntu 20.04 Quick Guide improvements

modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
=> [10.9] [PR 113] Ubuntu 20.04 Quick Guide improvements

modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
finalize -> finalize
original fix was for 10.9 only
backport to 10.8 needed
=> finalise typo

modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
=> [10.8] [PR 120] finalise typo

modules/admin_manual/pages/qnap/index.adoc
=> [10.9] [PR 123] fix occ usage on qnap

modules/admin_manual/pages/qnap/index.adoc
=> [10.8] [PR 123] fix occ usage on qnap

modules/admin_manual/pages/configuration/integration/ms-teams.adoc
Small fix
Backport to 10.9 only
=> Source language fix for MS Teams

modules/admin_manual/pages/configuration/server/harden_server.adoc, modules/admin_manual/pages/qnap/index.adoc
=> [10.9] [PR 128] Source language fix for harden server

modules/admin_manual/pages/configuration/server/harden_server.adoc, modules/admin_manual/pages/qnap/index.adoc
=> [10.8] [PR 128] Source language fix for harden server

modules/admin_manual/pages/configuration/integration/ms-teams.adoc
=> [10.9] [PR 129] Source language fix for MS Teams

modules/admin_manual/pages/installation/docker/index.adoc
Set the correct source language for docker install
=> Set the correct source language for docker install

modules/admin_manual/pages/configuration/database/db_conversion.adoc
=> [10.9] [PR 133] Updates to innodb tunning instructions,

modules/admin_manual/pages/configuration/database/db_conversion.adoc
=> [10.8] [PR 133] Updates to innodb tunning instructions,

modules/admin_manual/pages/maintenance/upgrading/update.adoc
=> [10.8] [PR 134] Update update.adoc

modules/admin_manual/pages/maintenance/upgrading/update.adoc
=> [master] [PR 134] Update update.adoc

modules/admin_manual/pages/installation/docker/index.adoc
=> [10.8] Set the correct source language for docker install

modules/admin_manual/pages/installation/docker/index.adoc
=> [10.9] Set the correct source language for docker install

modules/admin_manual/pages/appliance/configuration/index.php-less_URLs.adoc, modules/admin_manual/pages/appliance/configuration/login_information.adoc, modules/admin_manual/pages/appliance/configuration/wnd_setup.adoc, modules/admin_manual/pages/appliance/maintenance/backup.adoc, modules/admin_manual/pages/appliance/maintenance/howto-update-owncloud.adoc, modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_ldap_integration_commands.adoc, modules/admin_manual/pages/configuration/server/security/hsmdaemon/index.adoc, modules/admin_manual/pages/configuration/server/security/hsmdaemon/softhsm2.adoc
=> [10.9] [PR 148] Fix typo

modules/admin_manual/pages/appliance/configuration/index.php-less_URLs.adoc, modules/admin_manual/pages/appliance/configuration/login_information.adoc, modules/admin_manual/pages/appliance/configuration/wnd_setup.adoc, modules/admin_manual/pages/appliance/maintenance/backup.adoc, modules/admin_manual/pages/appliance/maintenance/howto-update-owncloud.adoc, modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_ldap_integration_commands.adoc, modules/admin_manual/pages/configuration/server/security/hsmdaemon/index.adoc, modules/admin_manual/pages/configuration/server/security/hsmdaemon/softhsm2.adoc
=> [10.8] [PR 148] Fix typo

modules/ROOT/partials/nav.adoc, site.yml
=> [10.9] [PR 151] Inactivate the user guide

modules/ROOT/partials/nav.adoc, site.yml
=> [10.8] [PR 151] Inactivate the user guide

modules/admin_manual/pages/configuration/files/external_storage/smb.adoc, modules/admin_manual/pages/configuration/server/index_php_less_urls.adoc, modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_ransomware_protection_commands.adoc, modules/admin_manual/pages/configuration/server/security/oauth2.adoc, modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc, modules/admin_manual/pages/installation/deployment_recommendations.adoc, modules/admin_manual/pages/installation/linux_packetmanager_install.adoc, modules/admin_manual/partials/maintenance/major_release_note.adoc, modules/developer_manual/pages/testing/test-pilots.adoc, modules/developer_manual/pages/webdav_api/files_versions.adoc
=> [10.9] [PR 157] Fix some broken links found after migrating the user manual

modules/admin_manual/pages/configuration/files/external_storage/smb.adoc, modules/admin_manual/pages/configuration/server/index_php_less_urls.adoc, modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_ransomware_protection_commands.adoc, modules/admin_manual/pages/configuration/server/security/oauth2.adoc, modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc, modules/admin_manual/pages/installation/deployment_recommendations.adoc, modules/admin_manual/pages/installation/linux_packetmanager_install.adoc, modules/admin_manual/partials/maintenance/major_release_note.adoc, modules/developer_manual/pages/testing/test-pilots.adoc, modules/developer_manual/pages/webdav_api/files_versions.adoc
=> [10.8] [PR 157] Fix some broken links found after migrating the user manual

modules/admin_manual/pages/configuration/search/index.adoc, modules/admin_manual/pages/configuration/server/security/oauth2.adoc
=> [10.9] [PR 161] Broken internal link fix

modules/admin_manual/pages/configuration/search/index.adoc, modules/admin_manual/pages/configuration/server/security/oauth2.adoc
=> [10.8] [PR 161] Broken internal link fix

modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
=> [10.8] [PR 164] fix: replace outdated wopi docs urls

modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
=> [10.9] [PR 164] fix: replace outdated wopi docs urls

modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
=> [10.8] [PR 167] Update ubuntu_20_04.adoc

modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
=> [10.9] [PR 167] Update ubuntu_20_04.adoc

modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
=> [10.9] [PR 168] Update ubuntu_20_04.adoc

modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
=> [10.8] [PR 168] Update ubuntu_20_04.adoc

modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
=> [10.9] [PR 173] Update ubuntu_20_04.adoc

modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
=> [10.8] [PR 173] Update ubuntu_20_04.adoc

modules/admin_manual/pages/document_classification/index.adoc, modules/admin_manual/pages/installation/deployment_recommendations/nfs.adoc, modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
`htmltest` reported some easy to fix exernal links resulting in a 404 - fixed
=> Fix external URL links resulting in 404

modules/admin_manual/pages/document_classification/index.adoc, modules/admin_manual/pages/installation/deployment_recommendations/nfs.adoc, modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
=> [10.9] [PR 176] Fix external URL links resulting in 404

modules/admin_manual/pages/document_classification/index.adoc, modules/admin_manual/pages/installation/deployment_recommendations/nfs.adoc, modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
=> [10.8] [PR 176] Fix external URL links resulting in 404

modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_18.04.adoc
Finally the last one fixable that is now fixed
No Backport
=> [10.8] Fix broken link for 10.8 only

modules/admin_manual/pages/configuration/database/linux_database_configuration.adoc
=> [10.9] [PR 180] Small text improvement for the linux database configuration document

modules/admin_manual/pages/configuration/database/linux_database_configuration.adoc
=> [10.8] [PR 180] Small text improvement for the linux database configuration document

modules/admin_manual/pages/installation/manual_installation/manual_installation_db.adoc
=> [10.9] [PR 185] expand install hints for postgresql (a bit)

modules/admin_manual/pages/installation/manual_installation/manual_installation_db.adoc
=> [10.8] [PR 185] expand install hints for postgresql (a bit)

modules/admin_manual/pages/enterprise/installation/oracle_db_configuration.adoc
=> [10.9] [PR 191] link to \"this guide\" added.

modules/admin_manual/pages/enterprise/installation/oracle_db_configuration.adoc
=> [10.8] [PR 191] link to \"this guide\" added.

modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_maintenance_commands.adoc
=> [10.9] [PR 189] Revision of the occ maintenance command description

modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_maintenance_commands.adoc
=> [10.8] [PR 189] Revision of the occ maintenance command description

modules/admin_manual/pages/enterprise/clients/creating_branded_apps.adoc
=> [10.9] [PR 198] Fix links to branded clients URL

modules/admin_manual/pages/enterprise/clients/creating_branded_apps.adoc
=> [10.8] [PR 198] Fix links to branded clients URL

modules/admin_manual/pages/appliance/configuration/clamav.adoc, modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc, modules/admin_manual/pages/installation/deployment_recommendations.adoc, modules/admin_manual/pages/installation/letsencrypt/using_letsencrypt.adoc
=> [10.9] [PR 202] Prepare quoted text to be Antora 3 compliant

modules/admin_manual/pages/appliance/configuration/clamav.adoc, modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc, modules/admin_manual/pages/installation/deployment_recommendations.adoc, modules/admin_manual/pages/installation/letsencrypt/using_letsencrypt.adoc
=> [10.8] [PR 202] Prepare quoted text to be Antora 3 compliant

modules/admin_manual/pages/installation/system_requirements.adoc
=> [10.9] [PR 206] Add support for pgsql 11 12 13 14

modules/admin_manual/pages/enterprise/external_storage/onedrive.adoc
=> [10.9] [PR 205] onedrive app is not a standard enterprise app

modules/admin_manual/pages/configuration/server/oc_server_tuning.adoc
=> [10.8] [PR 211] Update oc_server_tuning.adoc

modules/admin_manual/pages/configuration/server/oc_server_tuning.adoc
=> [10.9] [PR 211] Update oc_server_tuning.adoc

modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
- setting domain variable at the beginning for ease of configuration 
- pecl warnings mitigation
- transaction isolation
- performance schema
- password recommendations
- reduce ldap-sync cron job interval
- recommendation for mysqltuner & lets encrypt
=> More improvements for quick installation guide

modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
=> [10.9] [PR 212] More improvements for quick installation guide

modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
=> [10.8] [PR 212] More improvements for quick installation guide

modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
- added password generators for admin and db passwords
- updated the db creation and oC installation with variables containing passwords
- added an output of the password variables at the end
- added a link to the ownCloud instance at the end
=> add secure passwords

modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
=> [10.9] [PR 217] add secure passwords

modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
=> [10.8] [PR 217] add secure passwords

modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Headline capitalization needed fixing.
Backports to 10.9 and 10.8
=> Fixed headline capitalization

modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
=> [10.9] [PR 220] Fixed headline capitalization

modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
=> [10.8] [PR 220] Fixed headline capitalization

modules/admin_manual/pages/installation/system_requirements.adoc
=> [10.8] [PR 227] Update system_requirements.adoc

modules/admin_manual/pages/installation/system_requirements.adoc
=> [10.9] [PR 227] Update system_requirements.adoc

modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc
=> [10.9] [PR 234] Update general_troubleshooting.adoc

modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc
=> [10.8] [PR 234] Update general_troubleshooting.adoc

modules/admin_manual/pages/installation/manual_installation/manual_imagick7.adoc
=> [10.8] [PR 237] Update manual_imagick7.adoc

modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
=> put the user-key is legacy in the title

modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
=> [10.9] [PR 241] put the user-key is legacy in the title

modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
=> [10.8] [PR 241] put the user-key is legacy in the title

modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
Fixes: https://github.com/owncloud/docs-server/issues/250 (LDAP Filter for disabled users)
=> Fixes to user_auth_ldap

modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
=> [10.9] [PR 251] Fixes to user_auth_ldap

modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
=> [10.8] [PR 251] Fixes to user_auth_ldap

modules/admin_manual/pages/configuration/server/security/oauth2.adoc
=> [master] [PR 257] Update oauth2.adoc

modules/admin_manual/pages/configuration/server/security/oauth2.adoc
=> [10.8] [PR 257] Update oauth2.adoc

modules/admin_manual/pages/installation/docker/index.adoc, modules/admin_manual/pages/maintenance/backup_and_restore/backup.adoc
=> [10.9] [PR 260] MySQL Backup Use Single Transaction

modules/admin_manual/pages/installation/docker/index.adoc, modules/admin_manual/pages/maintenance/backup_and_restore/backup.adoc
=> [10.8] [PR 260] MySQL Backup Use Single Transaction

modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
=> [10.9] [PR 263] Add WOPI Business Key

modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
=> [10.8] [PR 263] Add WOPI Business Key

modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Reverts owncloud/docs-server#265
Needs reverting because of business security post disussion with @tbsbdr 
Also see: https://github.com/owncloud/docs-server/pull/255
=> Revert "[10.8] [PR 263] Add WOPI Business Key"

modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Reverts owncloud/docs-server#264
Needs reverting because of business security post disussion with @tbsbdr 
Also see: https://github.com/owncloud/docs-server/pull/255
=> Revert "[10.9] [PR 263] Add WOPI Business Key"

modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Reverts owncloud/docs-server#263
Needs reverting because of business security post disussion with @tbsbdr 
Also see: https://github.com/owncloud/docs-server/pull/255
=> Revert "Add WOPI Business Key"

modules/admin_manual/pages/enterprise/document_classification/classification_and_policy_enforcement.adoc, modules/admin_manual/pages/enterprise/document_classification/index.adoc, modules/admin_manual/partials/nav.adoc
=> [10.9] [PR 269] Relocate files_classifier document

modules/admin_manual/pages/enterprise/document_classification/classification_and_policy_enforcement.adoc, modules/admin_manual/pages/enterprise/document_classification/index.adoc, modules/admin_manual/partials/nav.adoc
=> [10.8] [PR 269] Relocate files_classifier document

modules/admin_manual/pages/configuration/user/user_oauth2.adoc
@mmattel Please take care of backports to all available versions.
=> Remove warning in OAuth2 doc

modules/admin_manual/pages/configuration/user/user_oauth2.adoc
=> [10.9] [PR 275] Remove warning in OAuth2 doc

modules/admin_manual/pages/installation/system_requirements.adoc
=> [master] [PR 280] Update system_requirements.adoc

modules/admin_manual/pages/installation/system_requirements.adoc
=> [10.8] [PR 280] Update system_requirements.adoc

modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
=> [10.9] [PR 286] Update manual_upgrade.adoc

modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
=> [10.8] [PR 286] Update manual_upgrade.adoc

site.yml
=> [10.9] [PR 293] Update site.yml

site.yml
=> [10.8] [PR 293] Update site.yml

modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Backport of #301 with special 10.9 adoptions
=> [10.9] [PR 301] Config To Docs run

modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Backport of #301 with special 10.8 changes
=> [10.8] [PR 301] Config To Docs run

modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
Add missing annotation of "apps" in text for changes of #285.
=> Update manual_upgrade.adoc (addendum to #285)

modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
=> [10.9] [PR 300] Update manual_upgrade.adoc (addendum to #285)

modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
=> [10.8] [PR 300] Update manual_upgrade.adoc (addendum to #285)

modules/admin_manual/pages/configuration/files/manual_file_locking.adoc
=> [10.9] [PR 307] Update the section for manual file locking in admin settings

modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
=> [10.8] [PR 313] Invert description of auto-app-update logic

modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
=> [10.9] [PR 313] Invert description of auto-app-update logic

modules/admin_manual/pages/configuration/files/external_storage/configuration.adoc
=> [10.10] [PR 312] mention enable files_external app

modules/admin_manual/pages/installation/manual_installation/manual_imagick7.adoc
=> [10.10] [PR 322] Just a small backlink to the previews configuration

modules/admin_manual/pages/installation/manual_installation/manual_imagick7.adoc
=> [10.9] [PR 322] Just a small backlink to the previews configuration

modules/admin_manual/pages/installation/manual_installation/manual_imagick7.adoc
=> [10.8] [PR 322] Just a small backlink to the previews configuration

site.yml
=> [10.10] [PR 327] Adding global attribute for ocis

site.yml
=> [10.9] [PR 327] Adding global attribute for ocis

site.yml
=> [10.8] [PR 327] Adding global attribute for ocis

modules/admin_manual/pages/configuration/server/email_configuration.adoc
custom theme required to edit mail templates
mail template app is required to edit mail templates
=> add note about custom theme

modules/admin_manual/pages/configuration/server/email_configuration.adoc
=> [10.10] [PR 326] add note about custom theme

modules/admin_manual/pages/configuration/server/email_configuration.adoc
=> [10.9] [PR 326] add note about custom theme

modules/admin_manual/pages/configuration/server/email_configuration.adoc
=> [10.8] [PR 326] add note about custom theme

modules/admin_manual/pages/enterprise/external_storage/enterprise_only_auth.adoc
=> [10.10] [PR 334] New syntax for config stored passwords

modules/admin_manual/pages/enterprise/external_storage/enterprise_only_auth.adoc
=> [10.9] [PR 334] New syntax for config stored passwords

.gitignore, modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc, modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
Added preliminary docs for the Office 365 integration
@jnweiger could you have a look if there is something missing as you just walked through the process
@mmattel please check if the docs is comprehensible and useful for users
=> O365 integration

.gitignore, modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc, modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
=> [10.10] [PR 255] O365 integration

.gitignore, modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc, modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
=> [10.8] [PR 255] O365 integration

.gitignore, modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc, modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
=> [10.9] [PR 255] O365 integration

modules/admin_manual/pages/enterprise/external_storage/sharepoint-integration_configuration.adoc
=> [10.10] [PR 233] updated php-soap instructions for sharepoint.

modules/admin_manual/pages/enterprise/external_storage/sharepoint-integration_configuration.adoc
=> [10.9] [PR 233] updated php-soap instructions for sharepoint.

modules/admin_manual/pages/enterprise/external_storage/sharepoint-integration_configuration.adoc
=> [10.8] [PR 233] updated php-soap instructions for sharepoint.

modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Fixing typos
Backport to 10.8, 10.9, 10.10
=> Language review sample php

modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
=> [10.9] [PR 343] Language review sample php

modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
=> [10.10] [PR 343] Language review sample php

modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
=> [10.8] [PR 348] Fixing ticks in msoffice-wopi

modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
=> [10.9] [PR 348] Fixing ticks in msoffice-wopi

modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
=> [10.10] [PR 348] Fixing ticks in msoffice-wopi

modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc, modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Config To Docs Run based on core PR: https://github.com/owncloud/core/pull/40079 (config.sample text changes)
Needs merging of the core PR first
=> config to docs run

modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc, modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
=> [10.8] [PR 353] config to docs run

modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc, modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
=> [10.9] [PR 353] config to docs run

modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc, modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
=> [10.10] [PR 353] config to docs run

modules/admin_manual/pages/enterprise/user_management/saml_2.0_sso.adoc
=> [10.10] [PR 358] Fix command line display on SAML page

modules/admin_manual/pages/installation/manual_installation/manual_installation_prerequisites.adoc, modules/admin_manual/pages/installation/system_requirements.adoc
=> [10.9] [PR 373] Temporary fix for the openSSL v3 incompatibility

modules/admin_manual/pages/installation/manual_installation/manual_installation_prerequisites.adoc, modules/admin_manual/pages/installation/system_requirements.adoc
=> [10.8] [PR 373] Temporary fix for the openSSL v3 incompatibility

modules/admin_manual/pages/configuration/user/oidc/ms-azure-setup.adoc, modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
=> [10.9] [PR 380] Fix typo

modules/admin_manual/pages/configuration/user/oidc/ms-azure-setup.adoc
Added a step for the platform configuration as this wasn't mentioned explicitly and I already faced wrong setups at this setup. It's important that is "Web" and nothing else for the browser to work.
=> More explicit description about platform config

modules/admin_manual/pages/configuration/user/oidc/ms-azure-setup.adoc
=> [10.10] [PR 386] More explicit description about platform config

modules/admin_manual/pages/configuration/user/oidc/ms-azure-setup.adoc
=> [10.9] [PR 386] More explicit description about platform config

modules/admin_manual/pages/configuration/server/caching_configuration.adoc
Updates the caching configuration.
=> Caching configuration update

modules/admin_manual/pages/configuration/server/caching_configuration.adoc
=> [10.9] [PR 389] Caching configuration update

modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
=> [10.10] [PR 393] Added description about handling in docker

modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
=> [10.8] [PR 393] Added description about handling in docker

modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc, modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_22.04.adoc, modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc, modules/admin_manual/pages/installation/quick_guides/ubuntu_22_04.adoc, modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
=> [10.10] [PR 401] Make the openSSL prerequisite more prominent

modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc, modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_22.04.adoc, modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc, modules/admin_manual/pages/installation/quick_guides/ubuntu_22_04.adoc, modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
=> [10.9] [PR 401] Make the openSSL prerequisite more prominent

modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc, modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_22.04.adoc, modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc, modules/admin_manual/pages/installation/quick_guides/ubuntu_22_04.adoc, modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
=> [10.8] [PR 401] Make the openSSL prerequisite more prominent

modules/admin_manual/pages/configuration/user/oidc/ms-azure-setup.adoc
=> [master] [PR 408] Fixed upper and lower case

modules/admin_manual/pages/configuration/user/oidc/ms-azure-setup.adoc
=> [10.9] [PR 408] Fixed upper and lower case

modules/admin_manual/pages/configuration/server/occ_command.adoc, modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_custom_groups.adoc, modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_config_commands.adoc, modules/admin_manual/pages/configuration/user/user_management.adoc
=> [10.8] [PR 411] occ custom groups

modules/admin_manual/pages/installation/linux_packetmanager_install.adoc, modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
=> fix: fix more deprecated download urls

modules/admin_manual/pages/installation/linux_packetmanager_install.adoc, modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
=> [10.10] [PR 415] fix: fix more deprecated download urls

modules/admin_manual/pages/installation/linux_packetmanager_install.adoc, modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
=> [10.9] [PR 415] fix: fix more deprecated download urls

modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
=> [10.10] [PR 418] update encryption

modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
=> [10.9] [PR 418] update encryption

modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
=> [10.8] [PR 418] update encryption

modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
=> [10.10] [PR 422] Added note about the user filter execution

modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
=> [10.9] [PR 422] Added note about the user filter execution

modules/admin_manual/pages/installation/letsencrypt/using_letsencrypt.adoc
=> [10.10] [PR 428] Update using_letsencrypt.adoc

modules/admin_manual/pages/installation/letsencrypt/using_letsencrypt.adoc
=> [10.9] [PR 428] Update using_letsencrypt.adoc

site.yml
=> [10.8] [PR 435] Current version is beta.3

site.yml
=> [10.9] [PR 435] Current version is beta.3

site.yml
=> [10.10] [PR 435] Current version is beta.3

modules/admin_manual/pages/configuration/database/db_conversion.adoc, modules/admin_manual/pages/configuration/server/security_setup_warnings.adoc
Fixes broken anchors found. One paragraph removed completely as outdated, reference deleted with: https://github.com/owncloud/docs-server/pull/226 (Updates to hardening guide)
=> Fixing broken anchors

modules/admin_manual/pages/configuration/database/db_conversion.adoc, modules/admin_manual/pages/configuration/server/security_setup_warnings.adoc
=> [10.10] [PR 439] Fixing broken anchors

modules/developer_manual/pages/testing/unit-testing.adoc
=> [10.10] [PR 442] fix phpunit url to prevent a 404

modules/developer_manual/pages/testing/unit-testing.adoc
=> [10.9] [PR 442] fix phpunit url to prevent a 404

modules/admin_manual/pages/enterprise/document_classification/classification_and_policy_enforcement.adoc
=> [10.10] [PR 445] fix vda url

modules/admin_manual/pages/enterprise/document_classification/classification_and_policy_enforcement.adoc
=> [10.9] [PR 445] fix vda url

modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
=> [10.9] [PR 451] Update files sharing configuration

modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
=> [10.9] [PR 450] Removed all occurrences of php prefixing

modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
=> [10.10] [PR 450] Removed all occurrences of php prefixing

modules/admin_manual/pages/maintenance/upgrading/update.adoc
Backports to 10.9 and 10.0 please
=> Updater control panel changed location

modules/admin_manual/pages/maintenance/upgrading/update.adoc
=> [10.10] [PR 456] Updater control panel changed location

modules/admin_manual/pages/maintenance/upgrading/update.adoc
=> [10.9] [PR 456] Updater control panel changed location

modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
Added documentation how to pass the workgroup name to occ wnd:listen command
=> Added documentation how to pass the workgroup name

modules/admin_manual/pages/configuration/user/reset_admin_password.adoc
=> Removed /var/www/owncloud/occ

modules/admin_manual/pages/configuration/user/reset_admin_password.adoc
=> [10.10] [PR 461] Removed /var/www/owncloud/occ

modules/admin_manual/pages/configuration/user/reset_admin_password.adoc
=> [10.9] [PR 461] Removed /var/www/owncloud/occ

modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
=> [10.9] [PR 459] Added documentation how to pass the workgroup name

modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
=> [10.10] [PR 459] Added documentation how to pass the workgroup name

modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
=> [10.9] [PR 460] Added description of password-from-service-account

modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
=> [10.10] [PR 460] Added description of password-from-service-account

modules/admin_manual/examples/installation/manual_installation/instance.sh, modules/admin_manual/examples/installation/manual_installation/owncloud_prep.sh, modules/admin_manual/pages/installation/manual_installation/script_guided_install.adoc
* Improves the upgrade script and the text, based on user feedback to make things more clear
* Add a database backup hint in the script when upgrading
* Added the capability to copy .json config files which are used for the new webUI
* Changed that all *config.php files will be copied and not only config.php as we can have multiple config files
Language review welcomed.
=> Improve upgrade script and text

modules/admin_manual/examples/installation/manual_installation/instance.sh, modules/admin_manual/examples/installation/manual_installation/owncloud_prep.sh, modules/admin_manual/pages/installation/manual_installation/script_guided_install.adoc
=> [10.10] [PR 468] Improve upgrade script and text

modules/admin_manual/examples/installation/manual_installation/instance.sh, modules/admin_manual/examples/installation/manual_installation/owncloud_prep.sh, modules/admin_manual/pages/installation/manual_installation/script_guided_install.adoc
=> [10.9] [PR 468] Improve upgrade script and text

modules/admin_manual/pages/configuration/server/occ_command.adoc, modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
=> [10.10] [PR 478] Fixing that occ needs to be set to executable if not already done.

modules/admin_manual/pages/configuration/server/occ_command.adoc, modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
=> [10.9] [PR 478] Fixing that occ needs to be set to executable if not already done.

modules/admin_manual/pages/installation/letsencrypt/apache.adoc
=> [10.10] [PR 476] Corrected upper and lower case

modules/admin_manual/pages/installation/letsencrypt/apache.adoc
=> [10.9] [PR 476] Corrected upper and lower case

modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
=> [10.10] [PR 475] Corrected rewrite rule

modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
=> [10.9] [PR 475] Corrected rewrite rule

modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
=> [10.10] [PR 492] Update the Virus Scanner page

modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
=> [10.9] [PR 492] Update the Virus Scanner page

modules/admin_manual/pages/configuration/server/security/jquery_warnings.adoc
=> [10.10] [PR 495] Update jQuery warnings page

modules/admin_manual/pages/configuration/server/security/jquery_warnings.adoc
=> [10.9] [PR 495] Update jQuery warnings page

modules/admin_manual/pages/enterprise/reporting/config_report.adoc, modules/admin_manual/partials/nav.adoc
=> [10.10] [PR 499] Add config report generation to enterprise

modules/admin_manual/pages/enterprise/reporting/config_report.adoc, modules/admin_manual/partials/nav.adoc
=> [10.9] [PR 499] Add config report generation to enterprise

modules/admin_manual/pages/configuration/user/user_management.adoc
=> [10.10] [PR 502] Update user_management.adoc

modules/admin_manual/pages/configuration/user/user_management.adoc
=> [10.9] [PR 502] Update user_management.adoc

modules/admin_manual/pages/installation/docker/index.adoc
Added documentation about docker run execution
=> Added documentation about docker run

modules/admin_manual/pages/installation/docker/index.adoc
=> [10.10] [PR 507] Added documentation about docker run

modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
=> [10.10] [PR 510] Config-to-docs run based on recent changes from core

modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
=> [10.9] [PR 510] Config-to-docs run based on recent changes from core

modules/admin_manual/pages/configuration/server/caching_configuration.adoc
=> [10.10] [PR 515] Make www-data a user in the redis group

modules/admin_manual/pages/configuration/server/caching_configuration.adoc
=> [10.9] [PR 515] Make www-data a user in the redis group

modules/admin_manual/pages/configuration/files/big_file_upload_configuration.adoc
=> [10.9] [PR 513] Corrected temp space calculation formula

modules/admin_manual/pages/configuration/files/big_file_upload_configuration.adoc
=> [10.9] [PR 503] Improved sentence about PHP output buffering

modules/admin_manual/pages/configuration/files/big_file_upload_configuration.adoc
=> [10.10] [PR 503] Improved sentence about PHP output buffering

modules/admin_manual/pages/installation/system_requirements.adoc, modules/admin_manual/partials/installation/manual_installation/mariadb.adoc
Backport of #530 to 10.10 branch.
=> [10.9] [PR 530] Document that ownCloud 10.9 and above also works with Mariadb 10.7 and 10.8

modules/admin_manual/pages/installation/system_requirements.adoc, modules/admin_manual/partials/installation/manual_installation/mariadb.adoc
Backport of #530 to 10.10 branch.
=> [10.10] [PR 530] Document that ownCloud 10.9 and above also works with Mariadb 10.7 and 10.8

modules/admin_manual/pages/configuration/general_topics/search.adoc
=> [10.9] [PR 533] Additional post-merge changes for #527

modules/admin_manual/examples/installation/docker/docker-compose.yml
=> [10.10] [PR 540] Increased mariadb version in docker compose file

modules/admin_manual/examples/installation/docker/docker-compose.yml
=> [10.9] [PR 540] Increased mariadb version in docker compose file

modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc, modules/admin_manual/pages/troubleshooting/general_troubleshooting.adoc
=> [10.9] [PR 545] Added note about overwritten .htaccess file

modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
=> [10.10] [PR 555] Config to docs run

modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
=> [10.9] [PR 555] Config to docs run

modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
=> [10.10] Config to Docs run

modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
=> [10.9] Config to Docs run

modules/admin_manual/pages/installation/docker/index.adoc
=> [10.10] [PR 563] Update generated volume name in index.adoc

modules/admin_manual/pages/installation/docker/index.adoc
=> [10.9] [PR 563] Update generated volume name in index.adoc

modules/admin_manual/pages/enterprise/logging/admin_audit.adoc
App needs log level 1 or 0 to work
Needs backporting.
=> Missing required configuration

modules/admin_manual/pages/enterprise/logging/admin_audit.adoc
=> [10.10] [PR 566] Missing required configuration

modules/admin_manual/pages/enterprise/logging/admin_audit.adoc
=> [10.9] [PR 566] Missing required configuration

modules/admin_manual/pages/enterprise/logging/admin_audit.adoc
Forgotten language fixes.
Backports to 10.10 and 10.9 necessary
=> language review

modules/admin_manual/pages/enterprise/logging/admin_audit.adoc
=> [10.10] [PR 569] language review

modules/admin_manual/pages/enterprise/logging/admin_audit.adoc
=> [10.9] [PR 569] language review

modules/developer_manual/pages/core/theming.adoc
=> Clarify setting of integrity.ignore.missing.app.signature

modules/developer_manual/pages/core/theming.adoc
=> [10.10] [PR 575] Clarify setting of integrity.ignore.missing.app.signature

modules/developer_manual/pages/core/theming.adoc
=> [10.9] [PR 575] Clarify setting of integrity.ignore.missing.app.signature

modules/admin_manual/pages/configuration/server/logging/logging_configuration.adoc, modules/admin_manual/pages/troubleshooting/providing_logs_and_config_files.adoc, modules/admin_manual/partials/nav.adoc, site.yml
=> [10.9] [PR 581] Fix configreport and logging

modules/admin_manual/pages/configuration/server/logging/logging_configuration.adoc, modules/admin_manual/pages/troubleshooting/providing_logs_and_config_files.adoc, modules/admin_manual/partials/nav.adoc, site.yml
=> [10.10] [PR 581] Fix configreport and logging

modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Fixes: #561 (config.apps.sample needs an update when openidconnect PR gets merged)
Needs merging of https://github.com/owncloud/core/pull/40260 (config.apps.sample changes) first.
No backport
@DeepDiver1975 @jnweiger fyi
Note, there are elements included of #524 which will go away when #524 gets merged and we rebase this one.
=> config.apps.sample changes via core

modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
=> [10.10] [PR 524] config apps sample update (openidconnect)

modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
=> [10.9] [PR 524] config apps sample update (openidconnect)

modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
=> [10.10] [PR 589] Config-to-docs run from latest core changes

modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
=> [10.9] [PR 589] Config-to-docs run from latest core changes

modules/admin_manual/pages/configuration/server/activity_configuration.adoc
=> [10.9] [PR 595] Update activity app

modules/admin_manual/pages/enterprise/installation/install.adoc
=> [10.9] [PR 548] User counting

modules/admin_manual/pages/installation/quick_guides/ubuntu_22_04.adoc
=> [master] [PR 599] Update ubuntu_22_04.adoc

modules/admin_manual/pages/installation/quick_guides/ubuntu_22_04.adoc
=> [10.9] [PR 599] Update ubuntu_22_04.adoc

modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
Referencing: #600 (Add recent core changes)
Updates the Secure View documentation.
=> Secure View update

modules/admin_manual/pages/enterprise/installation/install.adoc
=> [master] [PR 548] User counting

modules/admin_manual/pages/configuration/general_topics/impersonate_users.adoc
=> [10.10] [PR 607] Fix Impersonate not working with Shibboleth

modules/admin_manual/pages/configuration/general_topics/impersonate_users.adoc
=> [10.9] [PR 607] Fix Impersonate not working with Shibboleth

modules/admin_manual/pages/configuration/user/custom_groups_app.adoc
Addon to: https://github.com/owncloud/docs-server/pull/611 (Custom Groups)
Just a minor in-page link fix
No backport
=> Fix in-page link

modules/admin_manual/pages/configuration/server/occ_command.adoc, modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_managing_background_jobs.adoc, modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_previews_commands.adoc
=> [10.11] [PR 617] occ previews:cleanup

modules/admin_manual/pages/configuration/server/occ_command.adoc
=> [10.10] [PR 619] Fix occ source block

modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc, modules/admin_manual/pages/configuration/server/occ_command.adoc, modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_sharing_commands.adoc, modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_system_command.adoc
=> [10.10] [PR 624] Move occ system commands to the correct location

modules/admin_manual/pages/configuration/files/external_storage/local.adoc
=> [10.11] [PR 628] Update local.adoc

modules/admin_manual/pages/configuration/files/external_storage/local.adoc
=> [10.10] [PR 628] Update local.adoc

modules/admin_manual/pages/configuration/files/external_storage/local.adoc
=> [10.9] [PR 628] Update local.adoc

modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
=> [10.11] [PR 638] Config-to-docs Update

modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_previews_commands.adoc
=> [10.11] [PR 647] Preview cleanup update

modules/admin_manual/pages/installation/docker/index.adoc
=> [10.11] [PR 650] Add the supported database connectors to docker install

modules/admin_manual/pages/installation/docker/index.adoc
=> [10.10] [PR 650] Add the supported database connectors to docker install

modules/admin_manual/pages/configuration/general_topics/impersonate_users.adoc
=> Adjust text and examples for setting up the Impersonate app

modules/admin_manual/pages/configuration/general_topics/impersonate_users.adoc
=> [10.11] [PR 651] Adjust text and examples for setting up the Impersonate app

modules/admin_manual/pages/installation/docker/index.adoc
This PR corrects the technical wording about manually building an image with owncloud-server as base.
=> Small addition to #650

modules/admin_manual/pages/installation/docker/index.adoc
=> [10.11] [PR 655] Small addition to #650

modules/admin_manual/pages/installation/docker/index.adoc
=> [10.10] [PR 655] Small addition to #650

modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
=> [10.11] [PR 658] doc update for owncloud/core#40389

modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
=> [10.10] [PR 658] doc update for owncloud/core#40389

modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
Reverts owncloud/docs-server#659
References: https://github.com/owncloud/docs-server/pull/658#issuecomment-1266506261
=> Revert "[10.11] [PR 658] doc update for owncloud/core#40389"

modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
Reverts owncloud/docs-server#660
References: https://github.com/owncloud/docs-server/pull/658#issuecomment-1266506261
=> Revert "[10.10] [PR 658] doc update for owncloud/core#40389"

modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
Added an example configuration for Backblaze S3
=> Added Backblaze S3 primary example

modules/admin_manual/pages/configuration/integration/ms-teams.adoc
=> [10.10] [PR 669] fix apache header merge command

modules/admin_manual/pages/configuration/integration/ms-teams.adoc
=> [10.11] [PR 669] fix apache header merge command

modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
=> [10.10] [PR 670] add hint for db backups while using s3

modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
=> [10.11] [PR 670] add hint for db backups while using s3

modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
=> [master] [PR 666] Added Backblaze S3 primary example

modules/admin_manual/pages/enterprise/document_classification/classification_and_policy_enforcement.adoc
=> Add youtube video for document classification

modules/admin_manual/pages/enterprise/document_classification/classification_and_policy_enforcement.adoc
=> [10.11] [PR 677] Add youtube video for document classification

modules/admin_manual/pages/enterprise/document_classification/classification_and_policy_enforcement.adoc
=> [10.10] [PR 677] Add youtube video for document classification

modules/admin_manual/pages/qnap/index.adoc
- Add reverse proxy configuration for MyQnapCloud (which possibly works for other DDNS)
- Fixed default port and default directory for OwnCloud.
=> add MyQnapCloud configuration and reverse proxy

modules/admin_manual/pages/qnap/index.adoc
=> [10.11] [PR 676] add MyQnapCloud configuration and reverse proxy

modules/admin_manual/pages/qnap/index.adoc
=> [10.10] [PR 676] add MyQnapCloud configuration and reverse proxy

modules/admin_manual/pages/configuration/user/user_management.adoc
=> [10.11] [PR 683] Update the user management documentation

modules/admin_manual/pages/configuration/user/user_management.adoc
=> [10.10] [PR 683] Update the user management documentation

modules/admin_manual/pages/configuration/user/user_management.adoc
=> [10.11] [PR 686] Review of user_management page

modules/admin_manual/pages/configuration/user/user_management.adoc
=> [10.10] [PR 686] Review of user_management page

modules/admin_manual/pages/configuration/user/user_management.adoc
=> [10.11] [PR 687] Fixup quota explanation

modules/admin_manual/pages/configuration/user/user_management.adoc
=> [10.10] [PR 687] Fixup quota explanation

modules/admin_manual/examples/installation/docker/docker-compose.yml, modules/admin_manual/pages/installation/docker/index.adoc
=> [10.10] [PR 693] add documentation for trusted domain container env

modules/admin_manual/examples/installation/docker/docker-compose.yml, modules/admin_manual/pages/installation/docker/index.adoc
=> [10.11] [PR 693] add documentation for trusted domain container env

modules/admin_manual/pages/installation/manual_installation/manual_installation.adoc
fixes #698 
Backports done in:
#700 to 10.11
#701 to 10.10
=> Remove extra o from oowncloud

modules/admin_manual/pages/installation/manual_installation/manual_installation.adoc
=> [10.10] Remove extra o from oowncloud

modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
=> [10.11] [PR 705] Config to docs run

modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
=> [10.10] [PR 705] Config to docs run

modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
=> [10.11][704] Update S3 Primary documentation

modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
=> [10.10][704] Update S3 Primary documentation

modules/admin_manual/pages/configuration/user/user_auth_twofactor.adoc
=> [10.11] [PR 711] Clarify 2FA usage with desktop and mobile apps

modules/admin_manual/pages/configuration/user/user_auth_twofactor.adoc
=> [10.10] [PR 711] Clarify 2FA usage with desktop and mobile apps

modules/admin_manual/pages/maintenance/upgrading/upgrade.adoc
=> [10.11] [PR 710] Update upgrade.adoc

modules/admin_manual/pages/maintenance/upgrading/upgrade.adoc
=> [10.10] [PR 710] Update upgrade.adoc

modules/admin_manual/pages/configuration/server/security/oauth2.adoc, modules/admin_manual/pages/configuration/user/user_auth_twofactor.adoc
Referencing: #711 (Clarify 2FA usage with desktop and mobile apps)
Improves texts and links
=> Update 2FA and OAuth2

modules/admin_manual/pages/configuration/server/security/oauth2.adoc, modules/admin_manual/pages/configuration/user/user_auth_twofactor.adoc
=> [10.11] [PR 714] Update 2FA and OAuth2

modules/admin_manual/pages/configuration/server/security/oauth2.adoc, modules/admin_manual/pages/configuration/user/user_auth_twofactor.adoc
=> [10.10] [PR 714] Update 2FA and OAuth2

modules/admin_manual/pages/installation/letsencrypt/apache.adoc
=> [10.10] [PR 723] Fix VirtualHost parameter

modules/admin_manual/pages/installation/letsencrypt/apache.adoc
=> [10.11] [PR 723] Fix VirtualHost parameter

modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
Wow, strange that this server wants a completely differnet syntax.
=> Example USER DN

modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
=> [10.11] [PR 722] Example USER DN

modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
Fixes: #721 (clarification which product might work with ICAP needed)
Improved text for ICAP
=> Improve ICAP text

modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
=> [10.11] [PR 728] Improve ICAP text

modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
=> [10.10] [PR 728] Improve ICAP text

modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
=> [10.11] [PR 731] Config-to-docs run for openidconnect

modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
=> [10.10] [PR 731] Config-to-docs run for openidconnect

modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_file_commands.adoc
=> [10.11] [PR 743] Update files:scan not to be used with S3

modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_file_commands.adoc
=> [10.10] [PR 743] Update files:scan not to be used with S3

modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
=> [10.10] [PR 749] Files are also scanned on download

antora.yml
=> [10.11] [PR 752] Rename Classic Server (no reference changes)

modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
=> [10.10] [PR 758] Config-to-docs run for changes in core

modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
=> [10.11] [PR 758] Config-to-docs run for changes in core

modules/ROOT/pages/index.adoc
=> [10.10] [PR 765] Fix a remnant of the term classic

modules/admin_manual/pages/configuration/files/external_storage/configuration.adoc, modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc, modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_background_jobs_selector.adoc
On hint of @jnweiger (👍) , more improvements to this topic
=> More improvements for S3, files scan and BG jobs

modules/admin_manual/pages/configuration/files/external_storage/configuration.adoc, modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc, modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_background_jobs_selector.adoc
=> [10.10] [PR 768] More improvements for S3, files scan and BG jobs

modules/admin_manual/pages/configuration/files/external_storage/configuration.adoc, modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc, modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_background_jobs_selector.adoc
=> [10.11] [PR 768] More improvements for S3, files scan and BG jobs

modules/admin_manual/pages/configuration/user/guests_app.adoc
=> [10.11] [PR 772] Update of the guest app description

modules/admin_manual/pages/configuration/user/guests_app.adoc
=> [10.10] [PR 772] Update of the guest app description

modules/admin_manual/pages/configuration/general_topics/search.adoc, modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_full_text_search_commands.adoc, modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc, modules/admin_manual/pages/configuration/user/custom_groups_app.adoc
Fix broken internal links found via htmltest.
=> Fix broken (internal) links

modules/admin_manual/pages/configuration/general_topics/search.adoc, modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_full_text_search_commands.adoc, modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc, modules/admin_manual/pages/configuration/user/custom_groups_app.adoc
=> [10.11] [PR 775] Fix broken (internal) links

modules/admin_manual/pages/configuration/general_topics/search.adoc, modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_full_text_search_commands.adoc, modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
=> [10.10] [PR 775] Fix broken (internal) links

modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
=> [10.11] [PR 779] Add sudo on piped commands

modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
=> [10.10] [PR 779] Add sudo on piped commands

modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
=> [10.10] [PR 782] Apache rewriteRule requires mod_rewrite and no leading / in .htaccess

modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
=> [10.11] [PR 782] Apache rewriteRule requires mod_rewrite and no leading / in .htaccess

modules/admin_manual/pages/useful_pages.adoc, modules/admin_manual/partials/nav.adoc
=> [10.10] [PR 786] Create a Useful Pages page

modules/admin_manual/pages/useful_pages.adoc, modules/admin_manual/partials/nav.adoc
=> [10.11] [PR 786] Create a Useful Pages page

modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
Post a discussion with @tbsbdr we more granular describe which steps are required respectively made when using WOPI and Microsoft 365. This will help readers to understand who is providing what and why and how the final license check with Microsoft is done.
When the text is agreed, we will use the same one for the ocis version.
Language review welcomed.
No merge without approval from @tbsbdr 
=> Add WOPI Business Flow

modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
=> [10.11] [PR 789] Add WOPI Business Flow

modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
=> [10.10] [PR 789] Add WOPI Business Flow

modules/admin_manual/examples/installation/manual_installation/owncloud_prep.sh
=> [10.11] Fix small typo to make instructions less confusing

modules/admin_manual/examples/installation/manual_installation/owncloud_prep.sh
=> [10.10] Fix small typo to make instructions less confusing

modules/admin_manual/pages/installation/apps_supported.adoc
Adding Additional Enterprise Apps that are new or were not here before.
Backport to master and 10.10
=> Adding Additional Enterprise Apps

modules/admin_manual/pages/installation/apps_supported.adoc
=> [master] [PR 795] Adding Additional Enterprise Apps

modules/admin_manual/pages/installation/apps_supported.adoc
=> [10.10] [PR 795] Adding Additional Enterprise Apps

modules/admin_manual/pages/installation/apps_supported.adoc
=> [10.11] [PR 799] Update apps supported

modules/admin_manual/pages/installation/apps_supported.adoc
=> [10.10] [PR 799] Update apps supported

modules/admin_manual/pages/installation/quick_guides/ubuntu_22_04.adoc
=> [10.11] [PR 802] Update ubuntu_22_04.adoc

modules/admin_manual/pages/installation/quick_guides/ubuntu_22_04.adoc
=> [10.10] [PR 802] Update ubuntu_22_04.adoc

modules/admin_manual/pages/configuration/user/oidc/ms-azure-setup.adoc, modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
=> [10.11] [PR 806] [OIDC] Branded desktop and mobile clients for Azure AD

modules/admin_manual/pages/configuration/user/oidc/ms-azure-setup.adoc, modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
=> [10.10] [PR 806] [OIDC] Branded desktop and mobile clients for Azure AD

modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_maintenance_commands.adoc
=> [10.11] [PR 819] wrong command named

modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_maintenance_commands.adoc
=> [10.10] [PR 819] wrong command named

modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_ransomware_protection_commands.adoc, modules/admin_manual/pages/enterprise/security/ransomware-protection/index.adoc
=> [10.11] [PR 820] New occ ransomware command

modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_ransomware_protection_commands.adoc, modules/admin_manual/pages/enterprise/security/ransomware-protection/index.adoc
=> [10.10] [PR 820] New occ ransomware command

modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
References: #826 (Add Login Policies)
This updates config sample based on core changes: https://github.com/owncloud/core/pull/40609 ([docs-only] Fix config.sample.php)
No backport as this will come into 10.12
=> Config-to-Docs run with fixes

modules/admin_manual/pages/enterprise/external_storage/onedrive.adoc
=> [10.11] [PR 828] Hint for updated link names in onedrive.adoc

modules/admin_manual/pages/enterprise/external_storage/onedrive.adoc
=> [10.10] [PR 828] Hint for updated link names in onedrive.adoc

modules/admin_manual/pages/configuration/database/linux_database_configuration.adoc
=> [10.11] [PR 841] Update Configure MySQL for 4-byte Unicode Support

modules/admin_manual/pages/configuration/database/linux_database_configuration.adoc
=> [10.10] [PR 841] Update Configure MySQL for 4-byte Unicode Support

modules/admin_manual/pages/configuration/files/manual_file_locking.adoc
=> [10.10] [PR 844] Explain check-out, check-in by example

modules/admin_manual/pages/configuration/files/manual_file_locking.adoc
=> [10.11] [PR 844] Explain check-out, check-in by example

modules/ROOT/pages/index.adoc
=> [10.10] [PR 847] Also mention user guide?

modules/ROOT/pages/index.adoc
=> [10.11] [PR 847] Also mention user guide?

modules/admin_manual/pages/installation/manual_installation/manual_imagick7.adoc
=> [10.10] [PR 850] add notice about ImageMagick's scripting language (MSL)

modules/admin_manual/pages/installation/manual_installation/manual_imagick7.adoc
=> [10.11] [PR 850] add notice about ImageMagick's scripting language (MSL)

modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
=> [10.10] [PR 860] Update S3 concurrency example

modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
=> [10.11] [PR 860] Update S3 concurrency example

modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
=> [10.12] [PR 860] Update S3 concurrency example

modules/admin_manual/pages/configuration/general_topics/search.adoc
=> [10.10] [PR 866] Update the search app

modules/admin_manual/pages/configuration/general_topics/search.adoc
=> [10.12] [PR 866] Update the search app

modules/admin_manual/pages/installation/quick_guides/ubuntu_22_04.adoc
=> [10.10] [PR 870] remove extra backslash

modules/admin_manual/pages/installation/quick_guides/ubuntu_22_04.adoc
=> [10.11] [PR 870] remove extra backslash

modules/admin_manual/pages/installation/quick_guides/ubuntu_22_04.adoc
=> [10.12] [PR 870] remove extra backslash

modules/admin_manual/pages/installation/quick_guides/ubuntu_22_04.adoc
=> [10.10] [PR 871] escape variable

modules/admin_manual/pages/installation/quick_guides/ubuntu_22_04.adoc
=> [10.11] [PR 871] escape variable

modules/admin_manual/pages/installation/quick_guides/ubuntu_22_04.adoc
=> [10.12] [PR 871] escape variable

modules/admin_manual/pages/installation/quick_guides/ubuntu_22_04.adoc
=> [10.10] [PR 878] add testing of apache config

modules/admin_manual/pages/installation/quick_guides/ubuntu_22_04.adoc
=> [10.11] [PR 878] add testing of apache config

modules/admin_manual/pages/installation/quick_guides/ubuntu_22_04.adoc
=> [10.12] [PR 878] add testing of apache config

modules/admin_manual/pages/enterprise/firewall/file_firewall.adoc
=> [10.12] [PR 883] Update File-Firewall

modules/admin_manual/pages/enterprise/firewall/file_firewall.adoc
=> [10.10] [PR 883] Update File-Firewall

modules/admin_manual/pages/enterprise/firewall/file_firewall.adoc
=> [10.11] [PR 883] Update File-Firewall

modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
=> [10.12] [PR 888] Config-to-docs run

modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_ldap_integration_commands.adoc
=> [10.12] [PR 895] Document ldapNetworkTimeout

modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_ldap_integration_commands.adoc
=> [10.11] [PR 895] Document ldapNetworkTimeout

modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_ldap_integration_commands.adoc
=> [10.10] [PR 895] Document ldapNetworkTimeout

modules/admin_manual/pages/configuration/files/file_versioning.adoc
=> [10.12] [PR 903] Fix file_versions table

modules/admin_manual/pages/configuration/server/security/brute_force_protection.adoc
Fixes: #901 (Bruce force protection also applies to shares)
Adding a description where it applies.
@DeepDiver1975 Needs clarification if it also covers protection via client login - Keeping it as WIP atm.
Backport to 10.12 and 10.11
=> Update the brute force protection description

modules/admin_manual/pages/configuration/server/security/brute_force_protection.adoc
=> [10.12] [PR 902] Update the brute force protection description

modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
=> [10.12] [PR 906] Config to docs run based on recent changes from core

modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
=> [10.11] [PR 906] Config to docs run based on recent changes from core

modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
=> [10.11] [PR 909] Update s3_compatible_object_storage_as_primary.adoc

modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
=> [10.12] [PR 909] Update s3_compatible_object_storage_as_primary.adoc

modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
=> [10.12] [PR 912] Update encryption_configuration.adoc

modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
Reverts owncloud/docs-server#913
=> Revert "[10.12] [PR 912] Update encryption_configuration.adoc"

modules/developer_manual/pages/testing/ui-testing.adoc
forward-port #925 to master branch
fixes #924
=> [master] ui-testing.adoc - deprecate mailhog in favor of inbucket

modules/admin_manual/pages/installation/manual_installation/manual_installation_prerequisites.adoc
=> [10.11] [PR 934] added instructions how to enable legacy support

modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_22.04.adoc
=> [10.12] [PR 941] Changed order of pear & php-alternatives

modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_22.04.adoc
=> [10.11] [PR 941] Changed order of pear & php-alternatives

modules/admin_manual/pages/installation/letsencrypt/apache.adoc
=> [10.12] [PR 946] added enabling of ssl module to apache ssl configuration

modules/admin_manual/pages/installation/letsencrypt/apache.adoc
=> [10.11] [PR 946] added enabling of ssl module to apache ssl configuration

modules/admin_manual/pages/installation/manual_installation/manual_installation_prerequisites.adoc, modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc, modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_22.04.adoc, modules/admin_manual/pages/maintenance/upgrading/upgrade_php.adoc
=> [10.12] [PR 949] Change old references from PHP 7.3 to 7.4

modules/admin_manual/pages/installation/letsencrypt/apache.adoc
=> [10.11] [PR 957] added redirect permanent configuration

modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
=> [10.11] [PR 939] Document Desktop, Android and iOS app default scope and prompt parameters

modules/admin_manual/pages/installation/system_requirements.adoc
Backport #963 to oC core 10.11 docs branch
=> [10.11] Expand MariaDB support up to 10.11

modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
=> [10.12] [PR 969] layout fix for PR966

modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
=> [10.11] [PR 969] layout fix for PR966

modules/admin_manual/pages/installation/system_requirements.adoc
This PR adds the system requirements Redis
=> Added Redis requirements

modules/admin_manual/pages/installation/system_requirements.adoc
=> [10.11] [PR 972] Added Redis requirements

modules/admin_manual/pages/installation/system_requirements.adoc
=> [10.12] [PR 972] Added Redis requirements

modules/admin_manual/pages/enterprise/reporting/metrics.adoc
=> [10.11] [PR 980] Update metrics.adoc for PR #166

modules/admin_manual/pages/enterprise/reporting/metrics.adoc
=> [10.12] [PR 980] Update metrics.adoc for PR #166

modules/admin_manual/pages/configuration/files/mimetypes.adoc
=> [10.12] [PR 987] Remove trailing comma in JSON

modules/admin_manual/pages/configuration/files/mimetypes.adoc
=> [10.11] [PR 987] Remove trailing comma in JSON

modules/admin_manual/pages/configuration/files/big_file_upload_configuration.adoc
=> [10.11] [PR 992] Update big_file_upload_configuration.adoc

modules/admin_manual/pages/configuration/files/big_file_upload_configuration.adoc
=> [10.12] [PR 992] Update big_file_upload_configuration.adoc

modules/admin_manual/pages/configuration/server/legal_settings_configuration.adoc
=> Fix Broken Link

modules/admin_manual/pages/configuration/server/legal_settings_configuration.adoc
=> [10.12] [PR 1002] Fix Broken Link

modules/admin_manual/pages/configuration/user/oidc/ms-azure-setup.adoc
Added missing option about oAuth2 as a step before registration of the clients which only works with full branding sub
=> Update ms-azure-setup.adoc with oAuth2

modules/admin_manual/pages/configuration/user/oidc/ms-azure-setup.adoc
=> [10.12] [PR 1007] Update ms-azure-setup.adoc with oAuth2

modules/admin_manual/pages/configuration/user/oidc/ms-azure-setup.adoc
=> [10.11] [PR 1007] Update ms-azure-setup.adoc with oAuth2

site.yml
=> [10.11] [PR 1012] Add missing attributes in site.yml (local build relevant only)

site.yml
=> [10.12] [PR 1012] Add missing attributes in site.yml (local build relevant only)

modules/admin_manual/pages/index.adoc
The Youtube community channel is about to get closed - removing the link in docs.
@obibo2 FYI
=> Remove youtube community channel

.drone.star, modules/admin_manual/pages/installation/system_requirements.adoc
=> [10.11] [PR 1018] Update system_requirements, use MariaDB 10.11 as default

.drone.star, modules/admin_manual/pages/installation/system_requirements.adoc
=> [10.12] [PR 1018] Update system_requirements, use MariaDB 10.11 as default

modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
=> [10.12] [PR 1021] Update oidc.adoc

modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
=> [10.11] [PR 1021] Update oidc.adoc

modules/admin_manual/pages/index.adoc
=> [10.11] [PR 1020] Remove youtube community channel

modules/admin_manual/pages/index.adoc
=> [10.12] [PR 1020] Remove youtube community channel

modules/admin_manual/pages/configuration/server/email_configuration.adoc
=> [10.11] [PR 1030] Fix syntax of mail_smtpdebug example

modules/admin_manual/pages/maintenance/migrating.adoc
=> [10.11] [PR 1017] Added some hints how to survive the trusted_domains issue with docker

modules/admin_manual/pages/maintenance/migrating.adoc
=> [master] [PR 1017] Added some hints how to survive the trusted_domains issue with docker

site.yml
=> [10.11] [PR 1040] Update site.yml

site.yml
=> [10.12] [PR 1040] Update site.yml

modules/admin_manual/examples/installation/docker/docker-compose.yml, modules/admin_manual/pages/maintenance/upgrading/database_upgrade.adoc
=> Added MARIADB_AUTO_UPGRADE=1

modules/admin_manual/examples/installation/docker/docker-compose.yml, modules/admin_manual/pages/maintenance/upgrading/database_upgrade.adoc
=> [10.11] [PR 1045] Added MARIADB_AUTO_UPGRADE=1

modules/admin_manual/examples/installation/docker/docker-compose.yml, modules/admin_manual/pages/maintenance/upgrading/database_upgrade.adoc
=> [10.12] [PR 1045] Added MARIADB_AUTO_UPGRADE=1

modules/admin_manual/pages/configuration/general_topics/impersonate_users.adoc
=> [10.12] [PR 1037] Update impersonate_users.adoc

modules/admin_manual/pages/configuration/general_topics/impersonate_users.adoc
impersonate definitly works with openidconnect.
I cannot imagine a reason, why it should not work. Tested. Works fine.
It probably even works with shibleth. But I cannt easly test that.
=> Update impersonate_users.adoc opendconnect works

modules/admin_manual/pages/configuration/general_topics/impersonate_users.adoc
=> [10.11] [PR 1038] Update impersonate_users.adoc opendconnect works

modules/admin_manual/pages/configuration/general_topics/impersonate_users.adoc
=> [10.12] [PR 1038] Update impersonate_users.adoc opendconnect works

modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_data_exporter_commands.adoc, modules/admin_manual/pages/maintenance/export_import_instance_data.adoc
=> [10.11] [PR 1052] Document data exporter 236 last login timestamp behavior

modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_data_exporter_commands.adoc, modules/admin_manual/pages/maintenance/export_import_instance_data.adoc
=> [10.12] [PR 1052] Document data exporter 236 last login timestamp behavior

modules/admin_manual/pages/configuration/server/occ_command.adoc
=> [10.11] [PR 1057] Fix import name of occ cammand

modules/admin_manual/pages/configuration/user/user_roles.adoc
=> [10.11] [PR 1060] Update user_roles.adoc

modules/admin_manual/examples/installation/docker/docker-compose.yml, modules/admin_manual/pages/installation/docker/index.adoc
=> [10.11] [PR 1068] Update the Docker Compose section

modules/admin_manual/examples/installation/docker/docker-compose.yml, modules/admin_manual/pages/installation/docker/index.adoc
=> [10.12] [PR 1068] Update the Docker Compose section

modules/admin_manual/pages/installation/docker/index.adoc
References: #1068 
Just a mini fix, make it an own list item...
=> Mini fix for docker compose

modules/admin_manual/pages/installation/docker/index.adoc
=> [10.11] [PR 1071] Mini fix for docker compose

modules/admin_manual/pages/installation/docker/index.adoc
=> [10.12] [PR 1071] Mini fix for docker compose

modules/admin_manual/pages/installation/docker/index.adoc
=> [10.11] [PR 1075] Avoid Fairydust

modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
=> [10.12] [PR 1078] Update federated_cloud_sharing_configuration.adoc

modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
=> [master] [PR 1078] Update federated_cloud_sharing_configuration.adoc

modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
=> [10.13] [PR 1078] Update federated_cloud_sharing_configuration.adoc

modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
Reverts owncloud/docs-server#1079
=> Revert "[10.12] [PR 1078] Update federated_cloud_sharing_configuration.adoc"

modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
Reverts owncloud/docs-server#1078
=> Revert "Update federated_cloud_sharing_configuration.adoc"

modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
=> [master] [PR 1087] Update federated_cloud_sharing_configuration.adoc

modules/admin_manual/pages/configuration/server/occ_command.adoc, modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_federation_trusted_servers.adoc
=> [10.13] [PR 1090] Add new occ federation:trusted-servers

modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
While reading based on a question the WND docs, I identified that the WND docs need some love. This change eases maintenance now a lot. Note that the text was not changed, only the description added as attribute. Technically a language review is not necessary, but can be done if time permits.
* add description attribute
* image position
* image size
* space between text and table
* remove not necessary line breakes
* remove an outdated note
=> Update the WND page

modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
=> [10.12] [PR 1095] Update the WND page

modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc, modules/admin_manual/pages/installation/manual_installation/manual_installation_prerequisites.adoc
=> [10.12] [PR 1100] Update openssl

modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc, modules/admin_manual/pages/installation/manual_installation/manual_installation_prerequisites.adoc
=> [10.13] [PR 1100] Update openssl

modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc, modules/admin_manual/pages/installation/quick_guides/ubuntu_22_04.adoc, modules/admin_manual/partials/installation/manual_installation/mariadb.adoc, modules/admin_manual/partials/nav.adoc
=> [10.12] [PR 1103] Fix SQL commands when installing

modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc, modules/admin_manual/pages/installation/quick_guides/ubuntu_22_04.adoc, modules/admin_manual/partials/installation/manual_installation/mariadb.adoc, modules/admin_manual/partials/nav.adoc
=> [10.13] [PR 1103] Fix SQL commands when installing

modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
=> [10.13] [PR 1106] Update federated_cloud_sharing_configuration.adoc

modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
=> [10.12] [PR 1106] Update federated_cloud_sharing_configuration.adoc

modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
=> [10.12] [PR 1109] Fix typo in federated_cloud_sharing_configuration.adoc

modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
=> [10.13] [PR 1109] Fix typo in federated_cloud_sharing_configuration.adoc

modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
=> [10.13] [PR 1119] Fix encryption configuration page aliases

modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
=> [10.12] [PR 1119] Fix encryption configuration page aliases

modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Update config_apps_sample_php_parameters.adoc
=> Note about min 32 bytes, add  new wopi.proxy.key

modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
=> [10.13] [PR 1122] Note about min 32 bytes, add new wopi.proxy.key

modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
=> [10.12] [PR 1122] Note about min 32 bytes, add new wopi.proxy.key

modules/admin_manual/pages/enterprise/authentication/enterprise_only_auth.adoc, modules/admin_manual/pages/enterprise/clients/creating_branded_apps.adoc, modules/admin_manual/pages/enterprise/clients/index.adoc, modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc, modules/admin_manual/pages/enterprise/collaboration/index.adoc, modules/admin_manual/pages/enterprise/document_classification/classification_and_policy_enforcement.adoc, modules/admin_manual/pages/enterprise/document_classification/index.adoc, modules/admin_manual/pages/enterprise/external_storage/index.adoc, modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc, modules/admin_manual/pages/enterprise/file_management/files_tagging.adoc, modules/admin_manual/pages/enterprise/file_management/index.adoc, modules/admin_manual/pages/enterprise/firewall/file_firewall.adoc, modules/admin_manual/pages/enterprise/firewall/index.adoc, modules/admin_manual/pages/enterprise/index.adoc, modules/admin_manual/pages/enterprise/logging/admin_audit.adoc, modules/admin_manual/pages/enterprise/logging/index.adoc, modules/admin_manual/pages/enterprise/reporting/index.adoc, modules/admin_manual/pages/enterprise/reporting/metrics.adoc, modules/admin_manual/pages/enterprise/security/index.adoc, modules/admin_manual/pages/enterprise/security/ransomware-protection.adoc, modules/admin_manual/pages/enterprise/server_branding/enterprise_server_branding.adoc, modules/admin_manual/pages/enterprise/server_branding/index.adoc, modules/admin_manual/pages/enterprise/user_management/index.adoc, modules/admin_manual/pages/enterprise/user_management/saml_2.0_sso.adoc, modules/admin_manual/partials/nav.adoc
=> [10.13] [PR 1125] Remove all senseless index.adoc pages from the enterprise section

modules/admin_manual/pages/enterprise/authentication/enterprise_only_auth.adoc, modules/admin_manual/pages/enterprise/clients/creating_branded_apps.adoc, modules/admin_manual/pages/enterprise/clients/index.adoc, modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc, modules/admin_manual/pages/enterprise/collaboration/index.adoc, modules/admin_manual/pages/enterprise/document_classification/classification_and_policy_enforcement.adoc, modules/admin_manual/pages/enterprise/document_classification/index.adoc, modules/admin_manual/pages/enterprise/external_storage/index.adoc, modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc, modules/admin_manual/pages/enterprise/file_management/files_tagging.adoc, modules/admin_manual/pages/enterprise/file_management/index.adoc, modules/admin_manual/pages/enterprise/firewall/file_firewall.adoc, modules/admin_manual/pages/enterprise/firewall/index.adoc, modules/admin_manual/pages/enterprise/index.adoc, modules/admin_manual/pages/enterprise/logging/admin_audit.adoc, modules/admin_manual/pages/enterprise/logging/index.adoc, modules/admin_manual/pages/enterprise/reporting/index.adoc, modules/admin_manual/pages/enterprise/reporting/metrics.adoc, modules/admin_manual/pages/enterprise/security/index.adoc, modules/admin_manual/pages/enterprise/security/ransomware-protection.adoc, modules/admin_manual/pages/enterprise/server_branding/enterprise_server_branding.adoc, modules/admin_manual/pages/enterprise/server_branding/index.adoc, modules/admin_manual/pages/enterprise/user_management/index.adoc, modules/admin_manual/pages/enterprise/user_management/saml_2.0_sso.adoc, modules/admin_manual/partials/nav.adoc
=> [10.12] [PR 1125] Remove all senseless index.adoc pages from the enterprise section

modules/admin_manual/pages/configuration/server/security/jquery_warnings.adoc
jquery-ui "checkboxradio" is unused and not contained in ownCloud's jquery-ui bundle.
=> Add CVE-2022-31160 (checkboxradio) 

modules/admin_manual/pages/configuration/server/security/jquery_warnings.adoc
=> [10.13] [PR 1129] Add CVE-2022-31160 (checkboxradio)

modules/admin_manual/pages/configuration/server/security/jquery_warnings.adoc
=> [10.12] [PR 1129] Add CVE-2022-31160 (checkboxradio)

modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
=> [10.12] [PR 1134] Catch all app directories for updating permissions

modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
=> [10.13] [PR 1134] Catch all app directories for updating permissions

modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc, modules/admin_manual/pages/installation/quick_guides/ubuntu_22_04.adoc
=> [10.13] [PR 1131] Update ubuntu_20_04.adoc and ubuntu_22_04.adoc quickguides

modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc, modules/admin_manual/pages/installation/quick_guides/ubuntu_22_04.adoc
=> [10.12] [PR 1131] Update ubuntu_20_04.adoc and ubuntu_22_04.adoc quickguides

modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
=> [10.12] [PR 1149] added compelte ldaps doc, step by step

modules/admin_manual/pages/maintenance/manually-moving-data-folders.adoc
=> [10.13] [PR 1155] Update manually-moving-data-folders.adoc

modules/admin_manual/pages/maintenance/manually-moving-data-folders.adoc
=> [10.12] [PR 1155] Update manually-moving-data-folders.adoc

modules/admin_manual/pages/maintenance/backup_and_restore/backup.adoc, modules/admin_manual/pages/maintenance/backup_and_restore/restore.adoc
=> [10.12] [PR1153] added description to the fingerprint command and change title

modules/admin_manual/pages/maintenance/backup_and_restore/backup.adoc, modules/admin_manual/pages/maintenance/backup_and_restore/restore.adoc
=> [10.13] [PR1153] added description to the fingerprint command and change title

modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
=> [10.12] [PR 1169] Update collabora_secure_view.adoc

modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
=> [master] [PR 1169] Update collabora_secure_view.adoc

modules/admin_manual/pages/appliance/installation/installation.adoc
=> [10.13] [PR 1174] Update appliance installation.adoc

modules/admin_manual/pages/appliance/configuration/login_information.adoc
exact syntax for using cc with the appliance
=> Update appliance configuration  login_information.adoc

modules/admin_manual/pages/appliance/configuration/login_information.adoc
=> [10.12] [PR 1175] Update appliance configuration  login_information.adoc

modules/admin_manual/pages/appliance/configuration/firewall.adoc
=> [10.13] [PR 1176] Update appliance firewall.adoc

modules/admin_manual/pages/appliance/configuration/firewall.adoc
=> [10.12] [PR 1176] Update appliance firewall.adoc

modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc, modules/admin_manual/pages/installation/docker/index.adoc
=> [10.12] PR 1185] Updates config.sample and some docker related text

modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc, modules/admin_manual/pages/installation/docker/index.adoc
=> [10.13] [PR 1185] Updates config.sample and some docker related text

modules/admin_manual/pages/configuration/server/occ_command.adoc
=> [10.13] [PR 1183] Update occ_command.adoc

modules/admin_manual/pages/configuration/server/occ_command.adoc
=> [10.12] [PR 1183] Update occ_command.adoc

modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc, modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
=> [10.13] [PR 1190] Config-to-Docs run

modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc, modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
=> [10.12] [PR 1190] Config-to-Docs run

modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
=> [10.12] [PR 1193] Another necessary config to docs run

modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
=> [10.13] [PR 1193] Another necessary config to docs run

.gitignore, README.md, bin/prepare_site_yml
=> [10.12] [PR 1201] Update readme and prepare dev env

.gitignore, README.md, bin/prepare_site_yml
=> [10.13] [PR 1201] Update readme and prepare dev env

package.json
=> [10.12] [PR 1204] Update package.json

package.json
=> [10.13] [PR 1204] Update package.json

site.yml
=> [10.12] [PR 1212] Update site.yml

site.yml
=> [10.13] [PR 1212] Update site.yml

modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
This should crossrefernce to e.g. https://doc.owncloud.com/server/next/admin_manual/configuration/server/config_apps_sample_php_parameters.html#code-sample-35
=> limit 'chosen freely' in windows-network-drive_configuration.adoc

modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
=> [10.12] [PR 1216] limit 'chosen freely' in windows-network-drive_configuration.adoc

modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
=> [10.13] [PR 1216] limit 'chosen freely' in windows-network-drive_configuration.adoc

modules/admin_manual/pages/installation/apps_supported.adoc
=> [10.13] Fix faulty xrefs found during the antora upgrade

modules/admin_manual/pages/installation/apps_supported.adoc
=> [10.12] Fix faulty xrefs found during the antora upgrade

modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc, modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc, modules/admin_manual/pages/configuration/user/custom_groups_app.adoc, modules/admin_manual/pages/maintenance/upgrading/package_upgrade.adoc, modules/admin_manual/pages/maintenance/upgrading/update.adoc, modules/admin_manual/pages/maintenance/upgrading/upgrade.adoc, modules/admin_manual/pages/qnap/index.adoc
=> [10.12] [PR 1235] Fix links mostly to the server release notes

modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc, modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc, modules/admin_manual/pages/configuration/user/custom_groups_app.adoc, modules/admin_manual/pages/maintenance/upgrading/package_upgrade.adoc, modules/admin_manual/pages/maintenance/upgrading/update.adoc, modules/admin_manual/pages/maintenance/upgrading/upgrade.adoc, modules/admin_manual/pages/qnap/index.adoc
=> [10.13] [PR 1235] Fix links mostly to the server release notes

modules/admin_manual/partials/maintenance/major_release_note.adoc
=> [10.12] [PR 1238] One more xref to absolute path change

modules/admin_manual/partials/maintenance/major_release_note.adoc
=> [10.13] [PR 1238] One more xref to absolute path change

modules/admin_manual/pages/installation/apps_supported.adoc
See https://github.com/owncloud/templateeditor/issues/154
=> remove template editor from supported apps list

modules/admin_manual/pages/installation/apps_supported.adoc
=> [10.13] [PR 1231] remove template editor from supported apps list

modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
References: https://github.com/owncloud/core/pull/41148 (docs: update the wnd docs with new parameters)
References: https://github.com/owncloud/core/pull/41164 (docs: update config.apps.sample)
* WND/LDAP app update has been released
* Files PDF Viewer app update has been released
=> Config to docs run based on changes in core

modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
=> [10.13] [PR 1219] Config to docs run based on changes in core

modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
=> [10.12] [PR 1219] Config to docs run based on changes in core

modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
=> [master] [PR 1253] Update collabora_secure_view.adoc

docs/new-version-branch.md
=> [10.12] [PR 1255] Just a small internal link fix

ext-antora/generate-index.js
=> [10.13] [PR 1258] Fix search index generation

ext-antora/generate-index.js
Script update for consistency + small fixes.
Backport to 10.12 and 10.13
=> ES index update

ext-antora/generate-index.js
=> [10.13] [PR 1264] ES index update

ext-antora/generate-index.js
=> [10.12] [PR 1264] ES index update

modules/admin_manual/pages/configuration/files/previews_configuration.adoc
=> [10.12] [PR 1269] Update previews_configuration.adoc - PreviewProvider clarification

modules/admin_manual/pages/installation/system_requirements.adoc
=> [10.14] [PR 1277] Update system_requirements.adoc

modules/admin_manual/pages/installation/system_requirements.adoc
=> [10.13] [PR 1277] Update system_requirements.adoc

modules/developer_manual/pages/app/fundamentals/routes.adoc
=> [10.13] [PR 1244] Update routes.adoc

modules/developer_manual/pages/app/fundamentals/routes.adoc
=> [10.14] [PR 1244] Update routes.adoc

modules/admin_manual/pages/configuration/files/previews_configuration.adoc
=> [10.13] [PR 1283] Mention ghostscript dependency for PDF previews

modules/admin_manual/pages/configuration/files/previews_configuration.adoc
=> [10.14] [PR 1283] Mention ghostscript dependency for PDF previews

modules/admin_manual/pages/installation/system_requirements.adoc
=> [10.13] [PR 1287] Update system_requirements.adoc

modules/admin_manual/pages/installation/system_requirements.adoc
=> [10.14] [PR 1287] Update system_requirements.adoc

modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc, modules/admin_manual/pages/configuration/files/encryption/encryption_configuration_quick_guide.adoc, modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_encryption_commands.adoc, modules/admin_manual/pages/configuration/server/security/hsmdaemon/index.adoc, modules/admin_manual/pages/maintenance/encryption/migrating-from-user-key-to-master-key.adoc
=> [10.13] [PR 1290] fix: select encryption type is obsolete

.drone.star
=> [10.14] [PR 1295] chore: report CI result to builds channel

modules/developer_manual/pages/core/apis/ocs-share-api.adoc
=> [10.14] [PR 1299] clarify sharing bits

modules/developer_manual/pages/core/apis/ocs-share-api.adoc
=> [10.13] [PR 1299] clarify sharing bits

modules/admin_manual/pages/configuration/files/previews_configuration.adoc
=> [10.14] [1296] Update previews_configuration.adoc

modules/admin_manual/pages/maintenance/manually-moving-data-folders.adoc
=> [10.13] [PR 1229] Clarify and correct accounts table step

modules/admin_manual/pages/appliance/installation/installation.adoc
=> [master] [PR 1225] Update installation.adoc

modules/admin_manual/pages/appliance/installation/installation.adoc
=> [10.14] [PR 1225] Update installation.adoc

modules/admin_manual/pages/maintenance/manually-moving-data-folders.adoc
=> [10.14] [PR 1229] Clarify and correct accounts table step

modules/admin_manual/pages/configuration/files/encryption/encryption_configuration_quick_guide.adoc
=> [10.14] [PR 1298] Typo encryption_configuration_quick_guide.adoc

modules/admin_manual/pages/configuration/files/encryption/encryption_configuration_quick_guide.adoc
=> [10.13] [PR 1298] Typo encryption_configuration_quick_guide.adoc

modules/admin_manual/pages/installation/docker/index.adoc
=> [10.14] [PR 1197] Update docker install guide to use Compose v2

modules/developer_manual/pages/app/advanced/l10n.adoc
=> Update Transifex URL

modules/developer_manual/pages/app/advanced/l10n.adoc
=> [10.14] [PR 1320] Update Transifex URL

modules/developer_manual/pages/app/advanced/l10n.adoc
=> [10.13] [PR 1320] Update Transifex URL

modules/admin_manual/pages/maintenance/migrating_to_kiteworks.adoc
=> Update migrating_to_kiteworks.adoc fix verify cmd

modules/admin_manual/pages/maintenance/migrating_to_kiteworks.adoc
=> [10.15] [PR 1323] Update migrating_to_kiteworks.adoc fix verify cmd

modules/admin_manual/pages/maintenance/migrating_to_kiteworks.adoc
=> [10.14] [PR 1323] Update migrating_to_kiteworks.adoc fix verify cmd

modules/admin_manual/pages/maintenance/migrating_to_kiteworks.adoc
=> [10.14] [PR 1326] fix: rclone is bundled + guest users will be migrated

modules/admin_manual/pages/maintenance/migrating_to_kiteworks.adoc
=> [10.15] [PR 1326] fix: rclone is bundled + guest users will be migrated

modules/admin_manual/pages/maintenance/migrating_to_kiteworks.adoc
This has been touched a bit recently, so just cleaning up some small wording issues.
=> doc: review migrating to kiteworks

modules/admin_manual/pages/maintenance/migrating_to_kiteworks.adoc
=> [10.15] doc: review migrating to kiteworks

modules/admin_manual/pages/maintenance/migrating_to_kiteworks.adoc
=> [10.14] doc: review migrating to kiteworks

modules/admin_manual/pages/maintenance/migrating_to_kiteworks.adoc
When doing the backports of #1327 to;
10.15 #1333 
10.14 #1334 
I ended up fixing another "recommend having" that I had missed in the original PR #1327 
So this is a "forward port" of that little change to master.
Next time that I do a "text cleanup" like that, I will look at pending PRs, and wait until they are merged! That will be much easier than trying to sort out the conflicts.
=> fix: another 'recommend having'

modules/admin_manual/pages/maintenance/migrating_to_kiteworks.adoc
Add verbal description of the key elements seen in the screenshot of the kiteworks admin view. 
Mention the API Scopes, and give hint how to overcome that hurdle.
=> More details for migrating_to_kiteworks.adoc

modules/admin_manual/pages/maintenance/migrating_to_kiteworks.adoc
=> [10.15] [PR 1336] More details for migrating_to_kiteworks.adoc

modules/admin_manual/pages/maintenance/migrating_to_kiteworks.adoc
=> [10.14] [PR 1336] More details for migrating_to_kiteworks.adoc

modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
=> [10.15] [PR 1348] Config to docs run based on recent config sample changes

modules/developer_manual/pages/core/apis/ocs-share-api.adoc, modules/developer_manual/pages/general/codingguidelines.adoc
=> [10.15] [PR 1353] Fix two build error messages in dev docs

modules/developer_manual/pages/core/apis/ocs-share-api.adoc, modules/developer_manual/pages/general/codingguidelines.adoc
=> [10.14] [PR 1353] Fix two build error messages in dev docs

modules/developer_manual/pages/core/apis/ocs-share-api.adoc, modules/developer_manual/pages/general/codingguidelines.adoc
=> [10.13] [PR 1353] Fix two build error messages in dev docs

package.json, yarn.lock
=> [10.15] [PR 1357] Antora package.json refactoring

package.json, yarn.lock
=> [10.14] [PR 1357] Antora package.json refactoring

modules/admin_manual/pages/configuration/server/security/oauth2.adoc
=> [10.15] [PR 1342] clarify token_auth_enforced in oauth2.adoc

modules/admin_manual/pages/configuration/server/security/oauth2.adoc
=> [10.14] [PR 1342] clarify token_auth_enforced in oauth2.adoc

modules/admin_manual/pages/enterprise/authentication/kerberos.adoc
=> [10.15] [PR 1361] Change php-dev version used for Kerberos

modules/admin_manual/pages/enterprise/authentication/kerberos.adoc
=> [10.14] [PR 1361] Change php-dev version used for Kerberos

modules/admin_manual/pages/installation/manual_installation/script_guided_install.adoc
There is a number of details, that might not be obvious to everybody, e.g. the correct order of items to do. e.g. first maintenance mode and download, then start the script.  and no(!) backup of .htaccess (this fooled me so many times)
I guess my formatting is md, rather than adoc. sorry for this.
=> doc: example of script based upgrade added

modules/admin_manual/pages/installation/manual_installation/script_guided_install.adoc
=> [10.15] [PR 1368] doc: example of script based upgrade added

modules/admin_manual/pages/installation/manual_installation/script_guided_install.adoc
=> [master] [PR 1368] doc: example of script based upgrade added

modules/developer_manual/pages/testing/unit-testing.adoc
=> [10.14] [PR 1371] Fix rendering commands including proper resolving an attribute

modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
Added Wasabi based on the advice of a partner
=> Added Wasabi to s3_compatible_object_storage_as_primary.adoc

modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
=> [10.15] [PR 1375] Added Wasabi to s3_compatible_object_storage_as_primary.adoc

modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
=> [10.14] [PR 1375] Added Wasabi to s3_compatible_object_storage_as_primary.adoc

modules/admin_manual/pages/maintenance/manually-moving-data-folders.adoc
Typo fixes and add final step of scanning files for them to appear in the OwnCloud console.
=> Correct typos and add file scan step in manually-moving-data-folders.adoc

modules/admin_manual/pages/maintenance/manually-moving-data-folders.adoc
=> [10.15] [PR 1379] Correct typos and add file scan step in manually-moving-data-folders.adoc

modules/admin_manual/pages/maintenance/manually-moving-data-folders.adoc
=> [10.14] [PR 1379] Correct typos and add file scan step in manually-moving-data-folders.adoc

modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_data_exporter_commands.adoc
=> [10.14] [PR 1383] Fix data exporter occ command description

modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_data_exporter_commands.adoc
=> [10.15] [PR 1383] Fix data exporter occ command description

modules/admin_manual/pages/configuration/server/occ_command.adoc, modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_migrate_to_kitworks_commands.adoc, modules/admin_manual/pages/maintenance/migrating_to_kiteworks.adoc
=> [10.14] [PR 1382] Update Kiteworks migration documentation

modules/admin_manual/pages/maintenance/migrating_to_kiteworks.adoc
=> [10.14] [PR 1388] Codename Zion is internal. Use 8.6 instead

modules/admin_manual/pages/maintenance/migrating_to_kiteworks.adoc
=> [10.15] [PR 1388] Codename Zion is internal. Use 8.6 instead

modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
=> [10.14] [PR 1391] Add OIDC-ADFS client secret restriction

modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
=> [10.15] [PR 1391] Add OIDC-ADFS client secret restriction

modules/admin_manual/pages/maintenance/migrating_to_kiteworks.adoc
Fixes: #1396 (kiteworks migration enhancments)
New Kiteworks migration prerequisites as described in the referenced issue.
Backport to 10.14 and 10.15
=> Add new Kitworks migration prerequisites

modules/admin_manual/pages/maintenance/migrating_to_kiteworks.adoc
=> [10.15] [PR 1397] Add new Kitworks migration prerequisites

modules/admin_manual/pages/maintenance/migrating_to_kiteworks.adoc
=> [10.14] [PR 1397] Add new Kitworks migration prerequisites

modules/developer_manual/pages/webdav_api/search/_search_files.adoc
=> [10.14] [PR 1410] Fix including wrong filter example

modules/developer_manual/pages/webdav_api/search/_search_files.adoc
=> [10.15] [PR 1410] Fix including wrong filter example

ext-antora/comp-version.js
=> [10.15] [PR 1420] Update antora extension to print component, versions and files

ext-antora/comp-version.js
=> [10.14] [PR 1420] Update antora extension to print component, versions and files

modules/admin_manual/pages/configuration/server/security/jquery_warnings.adoc
=> [10.15] [PR 1423] Update CVEs

modules/admin_manual/pages/configuration/server/security/jquery_warnings.adoc
=> [10.14] [PR 1423] Update CVEs

modules/admin_manual/pages/configuration/server/security/dependency_notes.adoc, modules/admin_manual/partials/nav.adoc
=> [10.15] [PR 1431] Restructure dependency warnings/notes

ext-antora/comp-version.js
=> [10.14] [PR 1437] Update the component-version counting extension

ext-antora/comp-version.js
=> [10.15] [PR 1437] Update the component-version counting extension

modules/admin_manual/pages/configuration/server/security/dependency_notes.adoc
=> [10.14] [PR 1443] Add no vulnerability for two bootstrap CVE's

modules/admin_manual/pages/configuration/server/security/dependency_notes.adoc
=> [10.15] [PR 1443] Add no vulnerability for two bootstrap CVE's

modules/admin_manual/pages/configuration/integration/ms-teams.adoc, modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_config_reports_commands.adoc, modules/admin_manual/pages/installation/system_requirements.adoc
=> [10.14] [PR 1446] Remove or adapt support links

modules/admin_manual/pages/configuration/integration/ms-teams.adoc, modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_config_reports_commands.adoc, modules/admin_manual/pages/installation/system_requirements.adoc
=> [10.15] [PR 1446] Remove or adapt support links

docs/new-version-branch.md, docs/the-branching-workflow.md
=> [10.15] [PR 1449] Update the versioning process

docs/new-version-branch.md, docs/the-branching-workflow.md
=> [10.14] [PR 1449] Update the versioning process

modules/admin_manual/pages/maintenance/backup_and_restore/backup.adoc
=> [master] [PR 1452] Update backup.adoc

modules/admin_manual/pages/maintenance/backup_and_restore/backup.adoc
=> [10.14] [PR 1452] Update backup.adoc

modules/admin_manual/pages/maintenance/migrating_to_kiteworks.adoc
=> [10.14] [PR 1457] Update Kiteworks wording in migration

modules/admin_manual/pages/maintenance/migrating_to_kiteworks.adoc
=> [10.15] [PR 1457] Update Kiteworks wording in migration

modules/admin_manual/pages/configuration/server/harden_server.adoc, modules/admin_manual/pages/installation/manual_installation/manual_installation_db.adoc, modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc, modules/admin_manual/pages/installation/quick_guides/ubuntu_22_04.adoc
=> [10.15] [PR 1463] Add STRICT_TRANS_TABLES to MariaDB/MySQL

modules/admin_manual/pages/configuration/server/harden_server.adoc, modules/admin_manual/pages/installation/manual_installation/manual_installation_db.adoc, modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc, modules/admin_manual/pages/installation/quick_guides/ubuntu_22_04.adoc
=> [10.14] [PR 1463] Add STRICT_TRANS_TABLES to MariaDB/MySQL

modules/admin_manual/partials/nav.adoc
=> [10.14] [PR 1466] Fix PCN to PDN leftover
